/**
 * 课本单元词库 - 参照江苏译林版小学英语词汇难度进度整理
 * ⚠️ 请对照手头的实际教材核对每个单元单词，如有出入以教材为准
 */

// 快速创建词条
function w(word, meaning, phonetic, tip) {
    return {
        word,
        phonetic: phonetic || '',
        meaning,
        memoryTip: tip || '',
        difficulty: Math.min(Math.ceil(word.length / 3), 5)
    };
}

const curriculum = {

    // ============================================================
    // 三年级
    // ============================================================
    "三年级": {
        "上学期": {
            "Unit 1 Hello": [
                w("hello",   "你好",     "/həˈloʊ/"),
                w("hi",      "嗨",       "/haɪ/"),
                w("goodbye", "再见",     "/ˌɡʊdˈbaɪ/"),
                w("good",    "好的",     "/ɡʊd/"),
                w("morning", "早上",     "/ˈmɔːrnɪŋ/"),
                w("name",    "名字",     "/neɪm/"),
                w("I",       "我",       "/aɪ/"),
                w("am",      "是（我）", "/æm/"),
            ],
            "Unit 2 Nice to meet you": [
                w("meet",    "见面",     "/miːt/"),
                w("nice",    "很好的",   "/naɪs/"),
                w("you",     "你",       "/juː/"),
                w("too",     "也",       "/tuː/"),
                w("he",      "他",       "/hiː/"),
                w("she",     "她",       "/ʃiː/"),
                w("this",    "这",       "/ðɪs/"),
                w("is",      "是",       "/ɪz/"),
            ],
            "Unit 3 How are you": [
                w("how",     "怎么样",   "/haʊ/"),
                w("are",     "是",       "/ɑːr/"),
                w("fine",    "很好",     "/faɪn/"),
                w("thank",   "感谢",     "/θæŋk/"),
                w("very",    "非常",     "/ˈveri/"),
                w("well",    "好",       "/wel/"),
                w("great",   "很棒",     "/ɡreɪt/"),
                w("thanks",  "谢谢",     "/θæŋks/"),
            ],
            "Unit 4 I have a dream": [
                w("have",    "有",       "/hæv/"),
                w("dream",   "梦想",     "/driːm/"),
                w("want",    "想要",     "/wɒnt/"),
                w("be",      "成为",     "/biː/"),
                w("doctor",  "医生",     "/ˈdɒktər/"),
                w("farmer",  "农民",     "/ˈfɑːrmər/"),
                w("driver",  "司机",     "/ˈdraɪvər/"),
                w("cook",    "厨师",     "/kʊk/"),
            ],
            "Unit 5 Look at me": [
                w("look",    "看",       "/lʊk/"),
                w("at",      "在",       "/æt/"),
                w("tall",    "高的",     "/tɔːl/"),
                w("short",   "矮的",     "/ʃɔːrt/"),
                w("fat",     "胖的",     "/fæt/"),
                w("thin",    "瘦的",     "/θɪn/"),
                w("big",     "大的",     "/bɪɡ/"),
                w("small",   "小的",     "/smɔːl/"),
            ],
            "Unit 6 Colours": [
                w("red",     "红色",     "/red/"),
                w("yellow",  "黄色",     "/ˈjeloʊ/"),
                w("blue",    "蓝色",     "/bluː/"),
                w("green",   "绿色",     "/ɡriːn/"),
                w("white",   "白色",     "/waɪt/"),
                w("black",   "黑色",     "/blæk/"),
                w("pink",    "粉色",     "/pɪŋk/"),
                w("purple",  "紫色",     "/ˈpɜːrpl/"),
            ],
            "Unit 7 Toys": [
                w("toy",     "玩具",     "/tɔɪ/"),
                w("ball",    "球",       "/bɔːl/"),
                w("kite",    "风筝",     "/kaɪt/"),
                w("car",     "汽车",     "/kɑːr/"),
                w("doll",    "洋娃娃",   "/dɒl/"),
                w("robot",   "机器人",   "/ˈroʊbɒt/"),
                w("bike",    "自行车",   "/baɪk/"),
                w("game",    "游戏",     "/ɡeɪm/"),
            ],
            "Unit 8 Happy New Year": [
                w("happy",   "开心的",   "/ˈhæpi/"),
                w("new",     "新的",     "/njuː/"),
                w("year",    "年",       "/jɪər/"),
                w("wish",    "祝愿",     "/wɪʃ/"),
                w("family",  "家庭",     "/ˈfæməli/"),
                w("home",    "家",       "/hoʊm/"),
                w("gift",    "礼物",     "/ɡɪft/"),
                w("party",   "派对",     "/ˈpɑːrti/"),
            ],
        },
        "下学期": {
            "Unit 1 Animals": [
                w("cat",     "猫",       "/kæt/"),
                w("dog",     "狗",       "/dɒɡ/"),
                w("bird",    "鸟",       "/bɜːrd/"),
                w("fish",    "鱼",       "/fɪʃ/"),
                w("rabbit",  "兔子",     "/ˈræbɪt/"),
                w("monkey",  "猴子",     "/ˈmʌŋki/"),
                w("tiger",   "老虎",     "/ˈtaɪɡər/"),
                w("panda",   "熊猫",     "/ˈpændə/"),
            ],
            "Unit 2 Body parts": [
                w("head",    "头",       "/hed/"),
                w("eye",     "眼睛",     "/aɪ/"),
                w("ear",     "耳朵",     "/ɪər/"),
                w("nose",    "鼻子",     "/noʊz/"),
                w("mouth",   "嘴巴",     "/maʊθ/"),
                w("hand",    "手",       "/hænd/"),
                w("foot",    "脚",       "/fʊt/"),
                w("arm",     "手臂",     "/ɑːrm/"),
            ],
            "Unit 3 My school": [
                w("school",  "学校",     "/skuːl/"),
                w("book",    "书",       "/bʊk/"),
                w("pen",     "钢笔",     "/pen/"),
                w("pencil",  "铅笔",     "/ˈpensl/"),
                w("bag",     "书包",     "/bæɡ/"),
                w("ruler",   "尺子",     "/ˈruːlər/"),
                w("desk",    "书桌",     "/desk/"),
                w("chair",   "椅子",     "/tʃeər/"),
            ],
            "Unit 4 My family": [
                w("dad",     "爸爸",     "/dæd/"),
                w("mom",     "妈妈",     "/mɒm/"),
                w("brother", "兄弟",     "/ˈbrʌðər/"),
                w("sister",  "姐妹",     "/ˈsɪstər/"),
                w("grandpa", "爷爷",     "/ˈɡrændpɑː/"),
                w("grandma", "奶奶",     "/ˈɡrændmɑː/"),
                w("baby",    "婴儿",     "/ˈbeɪbi/"),
                w("son",     "儿子",     "/sʌn/"),
            ],
            "Unit 5 Fruit": [
                w("apple",   "苹果",     "/ˈæpl/"),
                w("banana",  "香蕉",     "/bəˈnɑːnə/"),
                w("orange",  "橙子",     "/ˈɒrɪndʒ/"),
                w("grape",   "葡萄",     "/ɡreɪp/"),
                w("peach",   "桃子",     "/piːtʃ/"),
                w("pear",    "梨",       "/peər/"),
                w("lemon",   "柠檬",     "/ˈlemən/"),
                w("mango",   "芒果",     "/ˈmæŋɡoʊ/"),
            ],
            "Unit 6 Numbers": [
                w("one",     "一",       "/wʌn/"),
                w("two",     "二",       "/tuː/"),
                w("three",   "三",       "/θriː/"),
                w("four",    "四",       "/fɔːr/"),
                w("five",    "五",       "/faɪv/"),
                w("six",     "六",       "/sɪks/"),
                w("seven",   "七",       "/ˈsevn/"),
                w("eight",   "八",       "/eɪt/"),
            ],
            "Unit 7 In the park": [
                w("park",    "公园",     "/pɑːrk/"),
                w("tree",    "树",       "/triː/"),
                w("flower",  "花",       "/ˈflaʊər/"),
                w("grass",   "草",       "/ɡrɑːs/"),
                w("run",     "跑",       "/rʌn/"),
                w("jump",    "跳",       "/dʒʌmp/"),
                w("play",    "玩",       "/pleɪ/"),
                w("climb",   "爬",       "/klaɪm/"),
            ],
            "Unit 8 Spring": [
                w("spring",  "春天",     "/sprɪŋ/"),
                w("warm",    "温暖的",   "/wɔːrm/"),
                w("sunny",   "晴朗的",   "/ˈsʌni/"),
                w("windy",   "有风的",   "/ˈwɪndi/"),
                w("rain",    "雨",       "/reɪn/"),
                w("cloud",   "云",       "/klaʊd/"),
                w("sky",     "天空",     "/skaɪ/"),
                w("sun",     "太阳",     "/sʌn/"),
            ],
        },
    },

    // ============================================================
    // 四年级
    // ============================================================
    "四年级": {
        "上学期": {
            "Unit 1 I like dogs": [
                w("like",    "喜欢",     "/laɪk/"),
                w("don't",   "不",       "/doʊnt/"),
                w("lion",    "狮子",     "/ˈlaɪən/"),
                w("bear",    "熊",       "/beər/"),
                w("snake",   "蛇",       "/sneɪk/"),
                w("frog",    "青蛙",     "/frɒɡ/"),
                w("duck",    "鸭子",     "/dʌk/"),
                w("sheep",   "羊",       "/ʃiːp/"),
            ],
            "Unit 2 I can do it": [
                w("can",     "能",       "/kæn/"),
                w("swim",    "游泳",     "/swɪm/"),
                w("ride",    "骑",       "/raɪd/"),
                w("sing",    "唱歌",     "/sɪŋ/"),
                w("dance",   "跳舞",     "/dɑːns/"),
                w("draw",    "画画",     "/drɔː/"),
                w("cook",    "做饭",     "/kʊk/"),
                w("fly",     "飞",       "/flaɪ/"),
            ],
            "Unit 3 What would you like": [
                w("would",   "想要",     "/wʊd/"),
                w("rice",    "米饭",     "/raɪs/"),
                w("noodle",  "面条",     "/ˈnuːdl/"),
                w("soup",    "汤",       "/suːp/"),
                w("bread",   "面包",     "/bred/"),
                w("egg",     "鸡蛋",     "/eɡ/"),
                w("milk",    "牛奶",     "/mɪlk/"),
                w("juice",   "果汁",     "/dʒuːs/"),
            ],
            "Unit 4 I love autumn": [
                w("autumn",  "秋天",     "/ˈɔːtəm/"),
                w("summer",  "夏天",     "/ˈsʌmər/"),
                w("winter",  "冬天",     "/ˈwɪntər/"),
                w("season",  "季节",     "/ˈsiːzn/"),
                w("hot",     "热的",     "/hɒt/"),
                w("cold",    "冷的",     "/koʊld/"),
                w("leaf",    "叶子",     "/liːf/"),
                w("fruit",   "水果",     "/fruːt/"),
            ],
            "Unit 5 Our school": [
                w("classroom","教室",    "/ˈklɑːsruːm/"),
                w("library", "图书馆",   "/ˈlaɪbreri/"),
                w("gym",     "体育馆",   "/dʒɪm/"),
                w("office",  "办公室",   "/ˈɒfɪs/"),
                w("garden",  "花园",     "/ˈɡɑːrdn/"),
                w("next",    "旁边",     "/nekst/"),
                w("near",    "靠近",     "/nɪər/"),
                w("behind",  "在后面",   "/bɪˈhaɪnd/"),
            ],
            "Unit 6 Whose gloves are these": [
                w("glove",   "手套",     "/ɡlʌv/"),
                w("hat",     "帽子",     "/hæt/"),
                w("coat",    "外套",     "/koʊt/"),
                w("scarf",   "围巾",     "/skɑːrf/"),
                w("whose",   "谁的",     "/huːz/"),
                w("these",   "这些",     "/ðiːz/"),
                w("those",   "那些",     "/ðoʊz/"),
                w("socks",   "袜子",     "/sɒks/"),
            ],
            "Unit 7 How much": [
                w("how",     "怎么",     "/haʊ/"),
                w("much",    "多少",     "/mʌtʃ/"),
                w("money",   "钱",       "/ˈmʌni/"),
                w("buy",     "买",       "/baɪ/"),
                w("sell",    "卖",       "/sel/"),
                w("cheap",   "便宜的",   "/tʃiːp/"),
                w("price",   "价格",     "/praɪs/"),
                w("yuan",    "元",       "/juːˈæn/"),
            ],
            "Unit 8 Christmas": [
                w("Christmas","圣诞节",  "/ˈkrɪsməs/"),
                w("tree",    "树",       "/triː/"),
                w("present", "礼物",     "/ˈpreznt/"),
                w("card",    "卡片",     "/kɑːrd/"),
                w("candle",  "蜡烛",     "/ˈkændl/"),
                w("snow",    "雪",       "/snoʊ/"),
                w("bell",    "铃铛",     "/bel/"),
                w("wish",    "祝愿",     "/wɪʃ/"),
            ],
        },
        "下学期": {
            "Unit 1 My day": [
                w("wake",    "醒来",     "/weɪk/"),
                w("get",     "起床",     "/ɡet/"),
                w("brush",   "刷牙",     "/brʌʃ/"),
                w("wash",    "洗",       "/wɒʃ/"),
                w("breakfast","早餐",    "/ˈbrekfəst/"),
                w("lunch",   "午餐",     "/lʌntʃ/"),
                w("dinner",  "晚餐",     "/ˈdɪnər/"),
                w("sleep",   "睡觉",     "/sliːp/"),
            ],
            "Unit 2 What time is it": [
                w("time",    "时间",     "/taɪm/"),
                w("o'clock", "点钟",     "/əˈklɒk/"),
                w("half",    "半",       "/hɑːf/"),
                w("past",    "过",       "/pɑːst/"),
                w("quarter", "一刻",     "/ˈkwɔːrtər/"),
                w("minute",  "分钟",     "/ˈmɪnɪt/"),
                w("hour",    "小时",     "/aʊər/"),
                w("clock",   "时钟",     "/klɒk/"),
            ],
            "Unit 3 How do you go to school": [
                w("bus",     "公共汽车", "/bʌs/"),
                w("train",   "火车",     "/treɪn/"),
                w("plane",   "飞机",     "/pleɪn/"),
                w("taxi",    "出租车",   "/ˈtæksi/"),
                w("subway",  "地铁",     "/ˈsʌbweɪ/"),
                w("walk",    "步行",     "/wɔːk/"),
                w("traffic", "交通",     "/ˈtræfɪk/"),
                w("road",    "路",       "/roʊd/"),
            ],
            "Unit 4 Our friends": [
                w("friend",  "朋友",     "/frend/"),
                w("kind",    "善良的",   "/kaɪnd/"),
                w("helpful", "乐于助人的","/ˈhelpfl/"),
                w("smart",   "聪明的",   "/smɑːrt/"),
                w("brave",   "勇敢的",   "/breɪv/"),
                w("cute",    "可爱的",   "/kjuːt/"),
                w("funny",   "有趣的",   "/ˈfʌni/"),
                w("honest",  "诚实的",   "/ˈɒnɪst/"),
            ],
            "Unit 5 My clothes": [
                w("shirt",   "衬衫",     "/ʃɜːrt/"),
                w("pants",   "裤子",     "/pænts/"),
                w("dress",   "连衣裙",   "/dres/"),
                w("skirt",   "裙子",     "/skɜːrt/"),
                w("shoes",   "鞋子",     "/ʃuːz/"),
                w("jacket",  "夹克",     "/ˈdʒækɪt/"),
                w("sweater", "毛衣",     "/ˈswetər/"),
                w("wear",    "穿",       "/weər/"),
            ],
            "Unit 6 Healthy food": [
                w("healthy", "健康的",   "/ˈhelθi/"),
                w("food",    "食物",     "/fuːd/"),
                w("meat",    "肉",       "/miːt/"),
                w("fish",    "鱼",       "/fɪʃ/"),
                w("vegetable","蔬菜",    "/ˈvedʒtəbl/"),
                w("water",   "水",       "/ˈwɔːtər/"),
                w("drink",   "喝",       "/drɪŋk/"),
                w("eat",     "吃",       "/iːt/"),
            ],
            "Unit 7 How are you feeling": [
                w("feel",    "感觉",     "/fiːl/"),
                w("happy",   "高兴的",   "/ˈhæpi/"),
                w("sad",     "伤心的",   "/sæd/"),
                w("angry",   "生气的",   "/ˈæŋɡri/"),
                w("tired",   "累的",     "/taɪərd/"),
                w("hungry",  "饿的",     "/ˈhʌŋɡri/"),
                w("thirsty", "渴的",     "/ˈθɜːrsti/"),
                w("excited", "兴奋的",   "/ɪkˈsaɪtɪd/"),
            ],
            "Unit 8 A birthday party": [
                w("birthday","生日",     "/ˈbɜːrθdeɪ/"),
                w("party",   "派对",     "/ˈpɑːrti/"),
                w("cake",    "蛋糕",     "/keɪk/"),
                w("candle",  "蜡烛",     "/ˈkændl/"),
                w("balloon", "气球",     "/bəˈluːn/"),
                w("sing",    "唱歌",     "/sɪŋ/"),
                w("blow",    "吹",       "/bloʊ/"),
                w("invite",  "邀请",     "/ɪnˈvaɪt/"),
            ],
        },
    },

    // ============================================================
    // 五年级
    // ============================================================
    "五年级": {
        "上学期": {
            "Unit 1 Goldilocks and the three bears": [
                w("goldilocks","金发姑娘",""),
                w("cottage",  "小屋",    "/ˈkɒtɪdʒ/"),
                w("porridge", "粥",      "/ˈpɒrɪdʒ/"),
                w("chair",    "椅子",    "/tʃeər/"),
                w("bear",     "熊",      "/beər/"),
                w("hard",     "硬的",    "/hɑːrd/"),
                w("soft",     "软的",    "/sɒft/"),
                w("cool",     "凉的",    "/kuːl/"),
            ],
            "Unit 2 A new student": [
                w("student",  "学生",    "/ˈstuːdnt/"),
                w("introduce","介绍",    "/ˌɪntrəˈdjuːs/"),
                w("subject",  "科目",    "/ˈsʌbdʒɪkt/"),
                w("maths",    "数学",    "/mæθs/"),
                w("science",  "科学",    "/ˈsaɪəns/"),
                w("art",      "美术",    "/ɑːrt/"),
                w("music",    "音乐",    "/ˈmjuːzɪk/"),
                w("English",  "英语",    "/ˈɪŋɡlɪʃ/"),
            ],
            "Unit 3 At a Music Hall": [
                w("music",    "音乐",    "/ˈmjuːzɪk/"),
                w("hall",     "大厅",    "/hɔːl/"),
                w("violin",   "小提琴",  "/ˌvaɪəˈlɪn/"),
                w("piano",    "钢琴",    "/piˈænoʊ/"),
                w("guitar",   "吉他",    "/ɡɪˈtɑːr/"),
                w("drum",     "鼓",      "/drʌm/"),
                w("flute",    "笛子",    "/fluːt/"),
                w("concert",  "音乐会",  "/ˈkɒnsərt/"),
            ],
            "Unit 4 Hobbies": [
                w("hobby",    "爱好",    "/ˈhɒbi/"),
                w("collect",  "收集",    "/kəˈlekt/"),
                w("stamp",    "邮票",    "/stæmp/"),
                w("model",    "模型",    "/ˈmɒdl/"),
                w("plant",    "种植",    "/plɑːnt/"),
                w("photograph","拍照",   "/ˈfoʊtəɡrɑːf/"),
                w("interested","感兴趣的","/ˈɪntrəstɪd/"),
                w("favorite", "最喜爱的","/ˈfeɪvərɪt/"),
            ],
            "Unit 5 A busy day": [
                w("busy",     "忙碌的",  "/ˈbɪzi/"),
                w("visit",    "参观",    "/ˈvɪzɪt/"),
                w("museum",   "博物馆",  "/mjuˈziːəm/"),
                w("shopping", "购物",    "/ˈʃɒpɪŋ/"),
                w("mall",     "购物中心","/mɔːl/"),
                w("tired",    "疲惫的",  "/taɪərd/"),
                w("early",    "早",      "/ˈɜːrli/"),
                w("late",     "晚",      "/leɪt/"),
            ],
            "Unit 6 My E-friend": [
                w("email",    "电子邮件","/ˈiːmeɪl/"),
                w("computer", "电脑",    "/kəmˈpjuːtər/"),
                w("message",  "信息",    "/ˈmesɪdʒ/"),
                w("send",     "发送",    "/send/"),
                w("receive",  "收到",    "/rɪˈsiːv/"),
                w("reply",    "回复",    "/rɪˈplaɪ/"),
                w("online",   "在线的",  "/ˈɒnlaɪn/"),
                w("keyboard", "键盘",    "/ˈkiːbɔːrd/"),
            ],
            "Unit 7 At weekends": [
                w("weekend",  "周末",    "/ˈwiːkend/"),
                w("usually",  "通常",    "/ˈjuːʒuəli/"),
                w("sometimes","有时候",  "/ˈsʌmtaɪmz/"),
                w("often",    "经常",    "/ˈɒfn/"),
                w("always",   "总是",    "/ˈɔːlweɪz/"),
                w("never",    "从不",    "/ˈnevər/"),
                w("relax",    "放松",    "/rɪˈlæks/"),
                w("enjoy",    "享受",    "/ɪnˈdʒɔɪ/"),
            ],
            "Unit 8 An interesting country": [
                w("country",  "国家",    "/ˈkʌntri/"),
                w("world",    "世界",    "/wɜːrld/"),
                w("map",      "地图",    "/mæp/"),
                w("capital",  "首都",    "/ˈkæpɪtl/"),
                w("language", "语言",    "/ˈlæŋɡwɪdʒ/"),
                w("population","人口",   "/ˌpɒpjuˈleɪʃn/"),
                w("famous",   "著名的",  "/ˈfeɪməs/"),
                w("culture",  "文化",    "/ˈkʌltʃər/"),
            ],
        },
        "下学期": {
            "Unit 1 The lion and the mouse": [
                w("lion",     "狮子",    "/ˈlaɪən/"),
                w("mouse",    "老鼠",    "/maʊs/"),
                w("rope",     "绳子",    "/roʊp/"),
                w("net",      "网",      "/net/"),
                w("escape",   "逃跑",    "/ɪˈskeɪp/"),
                w("help",     "帮助",    "/help/"),
                w("brave",    "勇敢的",  "/breɪv/"),
                w("free",     "自由的",  "/friː/"),
            ],
            "Unit 2 The environment": [
                w("environment","环境",  "/ɪnˈvaɪrənmənt/"),
                w("protect",  "保护",    "/prəˈtekt/"),
                w("recycle",  "回收",    "/ˌriːˈsaɪkl/"),
                w("pollution","污染",    "/pəˈluːʃn/"),
                w("clean",    "干净的",  "/kliːn/"),
                w("dirty",    "脏的",    "/ˈdɜːrti/"),
                w("rubbish",  "垃圾",    "/ˈrʌbɪʃ/"),
                w("save",     "节约",    "/seɪv/"),
            ],
            "Unit 3 Asking the way": [
                w("way",      "路",      "/weɪ/"),
                w("turn",     "转",      "/tɜːrn/"),
                w("left",     "左",      "/left/"),
                w("right",    "右",      "/raɪt/"),
                w("straight", "直走",    "/streɪt/"),
                w("cross",    "穿过",    "/krɒs/"),
                w("corner",   "转角",    "/ˈkɔːrnər/"),
                w("block",    "街区",    "/blɒk/"),
            ],
            "Unit 4 Seeing the doctor": [
                w("doctor",   "医生",    "/ˈdɒktər/"),
                w("headache", "头痛",    "/ˈhedeɪk/"),
                w("fever",    "发烧",    "/ˈfiːvər/"),
                w("cough",    "咳嗽",    "/kɒf/"),
                w("cold",     "感冒",    "/koʊld/"),
                w("medicine", "药",      "/ˈmedsn/"),
                w("rest",     "休息",    "/rest/"),
                w("better",   "好多了",  "/ˈbetər/"),
            ],
            "Unit 5 Meeting superheroes": [
                w("hero",     "英雄",    "/ˈhɪroʊ/"),
                w("supermarket","超市",  "/ˈsuːpərmɑːrkɪt/"),
                w("power",    "力量",    "/ˈpaʊər/"),
                w("amazing",  "令人惊叹的","/əˈmeɪzɪŋ/"),
                w("strong",   "强壮的",  "/strɒŋ/"),
                w("fast",     "快的",    "/fɑːst/"),
                w("fly",      "飞",      "/flaɪ/"),
                w("save",     "拯救",    "/seɪv/"),
            ],
            "Unit 6 A field trip": [
                w("field",    "田野",    "/fiːld/"),
                w("trip",     "旅行",    "/trɪp/"),
                w("butterfly","蝴蝶",    "/ˈbʌtərflaɪ/"),
                w("bee",      "蜜蜂",    "/biː/"),
                w("ant",      "蚂蚁",    "/ænt/"),
                w("pond",     "池塘",    "/pɒnd/"),
                w("frog",     "青蛙",    "/frɒɡ/"),
                w("insect",   "昆虫",    "/ˈɪnsekt/"),
            ],
            "Unit 7 Seasons": [
                w("season",   "季节",    "/ˈsiːzn/"),
                w("spring",   "春天",    "/sprɪŋ/"),
                w("summer",   "夏天",    "/ˈsʌmər/"),
                w("autumn",   "秋天",    "/ˈɔːtəm/"),
                w("winter",   "冬天",    "/ˈwɪntər/"),
                w("harvest",  "收获",    "/ˈhɑːrvɪst/"),
                w("snowman",  "雪人",    "/ˈsnoʊmæn/"),
                w("bloom",    "开花",    "/bluːm/"),
            ],
            "Unit 8 Summer holidays": [
                w("holiday",  "假期",    "/ˈhɒlɪdeɪ/"),
                w("travel",   "旅行",    "/ˈtrævl/"),
                w("beach",    "海滩",    "/biːtʃ/"),
                w("mountain", "山",      "/ˈmaʊntɪn/"),
                w("souvenir", "纪念品",  "/ˌsuːvəˈnɪər/"),
                w("camera",   "相机",    "/ˈkæmərə/"),
                w("memory",   "记忆",    "/ˈmeməri/"),
                w("excited",  "兴奋的",  "/ɪkˈsaɪtɪd/"),
            ],
        },
    },

    // ============================================================
    // 六年级
    // ============================================================
    "六年级": {
        "上学期": {
            "Unit 1 The king's new clothes": [
                w("king",     "国王",    "/kɪŋ/"),
                w("clothes",  "衣服",    "/kloʊðz/"),
                w("magic",    "魔法",    "/ˈmædʒɪk/"),
                w("invisible","隐形的",  "/ɪnˈvɪzəbl/"),
                w("honest",   "诚实的",  "/ˈɒnɪst/"),
                w("foolish",  "愚蠢的",  "/ˈfuːlɪʃ/"),
                w("laugh",    "笑",      "/lɑːf/"),
                w("truth",    "真相",    "/truːθ/"),
            ],
            "Unit 2 Good habits": [
                w("habit",    "习惯",    "/ˈhæbɪt/"),
                w("should",   "应该",    "/ʃʊd/"),
                w("exercise", "锻炼",    "/ˈeksərsaɪz/"),
                w("balance",  "平衡",    "/ˈbæləns/"),
                w("screen",   "屏幕",    "/skriːn/"),
                w("healthy",  "健康的",  "/ˈhelθi/"),
                w("bedtime",  "睡前",    "/ˈbedtaɪm/"),
                w("regularly","定期地",  "/ˈreɡjələrli/"),
            ],
            "Unit 3 Holiday fun": [
                w("Spring Festival","春节",""),
                w("lantern",  "灯笼",    "/ˈlæntərn/"),
                w("dragon",   "龙",      "/ˈdræɡən/"),
                w("dumpling", "饺子",    "/ˈdʌmplɪŋ/"),
                w("firework", "烟花",    "/ˈfaɪərwɜːrk/"),
                w("celebrate","庆祝",    "/ˈselɪbreɪt/"),
                w("tradition","传统",    "/trəˈdɪʃn/"),
                w("custom",   "习俗",    "/ˈkʌstəm/"),
            ],
            "Unit 4 Road safety": [
                w("safety",   "安全",    "/ˈseɪfti/"),
                w("danger",   "危险",    "/ˈdeɪndʒər/"),
                w("careful",  "小心的",  "/ˈkeərfl/"),
                w("signal",   "信号",    "/ˈsɪɡnəl/"),
                w("accident", "事故",    "/ˈæksɪdənt/"),
                w("helmet",   "头盔",    "/ˈhelmɪt/"),
                w("seatbelt", "安全带",  "/ˈsiːtbelt/"),
                w("rule",     "规则",    "/ruːl/"),
            ],
            "Unit 5 Signs": [
                w("sign",     "标志",    "/saɪn/"),
                w("notice",   "注意",    "/ˈnoʊtɪs/"),
                w("allowed",  "允许的",  "/əˈlaʊd/"),
                w("forbidden","禁止的",  "/fəˈbɪdən/"),
                w("entrance", "入口",    "/ˈentrəns/"),
                w("exit",     "出口",    "/ˈeksɪt/"),
                w("warning",  "警告",    "/ˈwɔːrnɪŋ/"),
                w("quiet",    "安静的",  "/ˈkwaɪət/"),
            ],
            "Unit 6 Keep our city clean": [
                w("litter",   "乱扔垃圾","/ˈlɪtər/"),
                w("rubbish",  "垃圾",    "/ˈrʌbɪʃ/"),
                w("bin",      "垃圾桶",  "/bɪn/"),
                w("recycle",  "回收利用","/ˌriːˈsaɪkl/"),
                w("reduce",   "减少",    "/rɪˈdjuːs/"),
                w("reuse",    "重复使用","/ˌriːˈjuːz/"),
                w("energy",   "能量",    "/ˈenərdʒi/"),
                w("volunteer","志愿者",  "/ˌvɒlənˈtɪər/"),
            ],
            "Unit 7 Protect animals": [
                w("protect",  "保护",    "/prəˈtekt/"),
                w("endangered","濒危的", "/ɪnˈdeɪndʒərd/"),
                w("wildlife", "野生动物","/ˈwaɪldlaɪf/"),
                w("extinct",  "灭绝的",  "/ɪkˈstɪŋkt/"),
                w("hunt",     "猎杀",    "/hʌnt/"),
                w("habitat",  "栖息地",  "/ˈhæbɪtæt/"),
                w("reserve",  "保护区",  "/rɪˈzɜːrv/"),
                w("precious", "珍贵的",  "/ˈpreʃəs/"),
            ],
            "Unit 8 Chinese New Year": [
                w("lunar",    "农历的",  "/ˈluːnər/"),
                w("reunion",  "团圆",    "/ˌriːˈjuːnjən/"),
                w("ancestor", "祖先",    "/ˈænsestər/"),
                w("blessing", "祝福",    "/ˈblesɪŋ/"),
                w("prosperity","繁荣",   "/prɒˈsperəti/"),
                w("wealth",   "财富",    "/welθ/"),
                w("lucky",    "幸运的",  "/ˈlʌki/"),
                w("harvest",  "丰收",    "/ˈhɑːrvɪst/"),
            ],
        },
        "下学期": {
            "Unit 1 The lion and the mouse": [
                w("roar",     "吼叫",    "/rɔːr/"),
                w("trapped",  "被困的",  "/træpt/"),
                w("promise",  "承诺",    "/ˈprɒmɪs/"),
                w("gnaw",     "啃",      "/nɔː/"),
                w("thankful", "感谢的",  "/ˈθæŋkfl/"),
                w("remember", "记住",    "/rɪˈmembər/"),
                w("kindness", "善意",    "/ˈkaɪndnəs/"),
                w("reward",   "回报",    "/rɪˈwɔːrd/"),
            ],
            "Unit 2 School life in the UK": [
                w("uniform",  "校服",    "/ˈjuːnɪfɔːrm/"),
                w("timetable","时间表",  "/ˈtaɪmteɪbl/"),
                w("term",     "学期",    "/tɜːrm/"),
                w("assembly", "集会",    "/əˈsembli/"),
                w("club",     "社团",    "/klʌb/"),
                w("break",    "课间休息","/breɪk/"),
                w("canteen",  "食堂",    "/kænˈtiːn/"),
                w("homework", "家庭作业","/ˈhoʊmwɜːrk/"),
            ],
            "Unit 3 A trip to space": [
                w("space",    "太空",    "/speɪs/"),
                w("planet",   "星球",    "/ˈplænɪt/"),
                w("rocket",   "火箭",    "/ˈrɒkɪt/"),
                w("astronaut","宇航员",  "/ˈæstrənɔːt/"),
                w("gravity",  "重力",    "/ˈɡrævɪti/"),
                w("orbit",    "轨道",    "/ˈɔːrbɪt/"),
                w("universe", "宇宙",    "/ˈjuːnɪvɜːrs/"),
                w("telescope","望远镜",  "/ˈtelɪskoʊp/"),
            ],
            "Unit 4 Indian and Indian food": [
                w("spice",    "香料",    "/spaɪs/"),
                w("curry",    "咖喱",    "/ˈkɜːri/"),
                w("recipe",   "食谱",    "/ˈresɪpi/"),
                w("ingredient","原料",   "/ɪnˈɡriːdiənt/"),
                w("flavour",  "味道",    "/ˈfleɪvər/"),
                w("delicious","美味的",  "/dɪˈlɪʃəs/"),
                w("national", "国家的",  "/ˈnæʃənl/"),
                w("dish",     "菜肴",    "/dɪʃ/"),
            ],
            "Unit 5 Harvey to the rescue": [
                w("rescue",   "救援",    "/ˈreskjuː/"),
                w("emergency","紧急情况","/ɪˈmɜːrdʒənsi/"),
                w("ambulance","救护车",  "/ˈæmbjuləns/"),
                w("accident", "意外",    "/ˈæksɪdənt/"),
                w("brave",    "勇敢的",  "/breɪv/"),
                w("quick",    "迅速的",  "/kwɪk/"),
                w("call",     "打电话",  "/kɔːl/"),
                w("safe",     "安全的",  "/seɪf/"),
            ],
            "Unit 6 An interesting country": [
                w("ancient",  "古老的",  "/ˈeɪnʃənt/"),
                w("modern",   "现代的",  "/ˈmɒdərn/"),
                w("sight",    "景点",    "/saɪt/"),
                w("attract",  "吸引",    "/əˈtrækt/"),
                w("tourist",  "游客",    "/ˈtʊərɪst/"),
                w("legend",   "传说",    "/ˈledʒənd/"),
                w("discover", "发现",    "/dɪˈskʌvər/"),
                w("wonder",   "奇迹",    "/ˈwʌndər/"),
            ],
            "Unit 7 Goodbye, my school": [
                w("graduate", "毕业",    "/ˈɡrædʒueɪt/"),
                w("memory",   "记忆",    "/ˈmeməri/"),
                w("treasure", "珍视",    "/ˈtreʒər/"),
                w("appreciate","感激",   "/əˈpriːʃieɪt/"),
                w("friendship","友情",   "/ˈfrendʃɪp/"),
                w("forever",  "永远",    "/fərˈevər/"),
                w("growth",   "成长",    "/ɡroʊθ/"),
                w("proud",    "骄傲的",  "/praʊd/"),
            ],
            "Unit 8 Our future lives": [
                w("future",   "未来",    "/ˈfjuːtʃər/"),
                w("dream",    "梦想",    "/driːm/"),
                w("achieve",  "实现",    "/əˈtʃiːv/"),
                w("goal",     "目标",    "/ɡoʊl/"),
                w("effort",   "努力",    "/ˈefərt/"),
                w("success",  "成功",    "/səkˈses/"),
                w("believe",  "相信",    "/bɪˈliːv/"),
                w("hope",     "希望",    "/hoʊp/"),
            ],
        },
    },
};
