// 江苏译林版小学英语词表 1A-6B
// 单词来源：教材配套词表

function w(word, phonetic, meaning) {
    return { word, phonetic, meaning, memoryTip: '', difficulty: Math.min(Math.ceil(word.replace(/ /g,'').length / 3), 5) };
}

const curriculum = {
    "一年级": {
        "上学期": {
            "Unit 1 Hello!": [
                w("hello", "/həˈləʊ/", "你好"),
                w("hi", "/haɪ/", "你好"),
                w("I'm", "/aɪm/", "我是"),
            ],
            "Unit 2 Good morning!": [
                w("Good morning", "/ɡʊd ˈmɔːnɪŋ/", "早上好"),
                w("Good afternoon", "/ɡʊd ˌɑːftəˈnuːn/", "下午好"),
                w("Good evening", "/ɡʊd ˈiːvnɪŋ/", "晚上好"),
                w("Good night", "/ɡʊd naɪt/", "晚安"),
                w("morning", "/ˈmɔːnɪŋ/", "早上"),
                w("afternoon", "/ˌɑːftəˈnuːn/", "下午"),
                w("evening", "/ˈiːvnɪŋ/", "晚上"),
                w("night", "/naɪt/", "夜晚"),
            ],
            "Unit 3 My family": [
                w("Miss", "/mɪs/", "小姐；老师"),
                w("mum", "/mʌm/", "妈妈"),
                w("dad", "/dæd/", "爸爸"),
                w("this", "/ðɪs/", "这；这个"),
                w("is", "/ɪz/", "是"),
                w("goodbye", "/ˌɡʊdˈbaɪ/", "再见"),
                w("Mr", "/ˈmɪstə/", "先生"),
            ],
            "Unit 4 Is this you?": [
                w("a", "/ə/", "一（个）"),
                w("teddy", "/ˈtedi/", "泰迪熊"),
                w("box", "/bɒks/", "盒子"),
                w("yes", "/jes/", "是；对"),
                w("bag", "/bæɡ/", "包"),
                w("no", "/nəʊ/", "不；不是"),
                w("puppy", "/ˈpʌpi/", "小狗"),
            ],
            "Unit 5 Look at me!": [
                w("cherry", "/ˈtʃeri/", "樱桃"),
                w("please", "/pliːz/", "请"),
                w("banana", "/bəˈnɑːnə/", "香蕉"),
                w("peach", "/piːtʃ/", "桃子"),
                w("grape", "/ɡreɪp/", "葡萄"),
                w("OK", "/əʊˈkeɪ/", "好的"),
                w("thank you", "/θæŋk juː/", "谢谢你"),
                w("look", "/lʊk/", "看"),
            ],
            "Unit 6 I like…": [
                w("balloon", "/bəˈluːn/", "气球"),
                w("pink", "/pɪŋk/", "粉红色的"),
                w("blue", "/bluː/", "蓝色的"),
                w("red", "/red/", "红色的"),
                w("green", "/ɡriːn/", "绿色的"),
                w("yellow", "/ˈjeləʊ/", "黄色的"),
                w("white", "/waɪt/", "白色的"),
            ],
            "Unit 7 It's…": [
                w("robot", "/ˈrəʊbɒt/", "机器人"),
                w("dance", "/dɑːns/", "跳舞"),
                w("sing", "/sɪŋ/", "唱歌"),
                w("draw", "/drɔː/", "绘画"),
                w("great", "/ɡreɪt/", "太棒了"),
                w("cook", "/kʊk/", "烹饪"),
            ],
            "Unit 8 What's this?": [
                w("cat", "/kæt/", "猫"),
                w("dog", "/dɒɡ/", "狗"),
                w("bird", "/bɜːd/", "鸟"),
                w("tiger", "/ˈtaɪɡə/", "老虎"),
                w("panda", "/ˈpændə/", "熊猫"),
                w("bear", "/beə/", "熊"),
            ],
        },
        "下学期": {
            "Unit 1 Let's count!": [
                w("let's", "/lets/", "让我们"),
                w("count", "/kaʊnt/", "数数"),
                w("how many", "/haʊ ˈmeni/", "多少"),
                w("marble", "/ˈmɑːbl/", "弹珠"),
                w("one", "/wʌn/", "一"),
                w("two", "/tuː/", "二"),
                w("three", "/θriː/", "三"),
                w("four", "/fɔː/", "四"),
                w("five", "/faɪv/", "五"),
                w("yellow", "/ˈjeləʊ/", "黄色的"),
            ],
            "Unit 2 My things": [
                w("pencil", "/ˈpensl/", "铅笔"),
                w("book", "/bʊk/", "书"),
                w("ruler", "/ˈruːlə/", "尺子"),
                w("rubber", "/ˈrʌbə/", "橡皮"),
                w("my", "/maɪ/", "我的"),
                w("sorry", "/ˈsɒri/", "对不起"),
                w("thank", "/θæŋk/", "谢谢"),
                w("you", "/juː/", "你"),
                w("your", "/jɔː/", "你的"),
                w("friend", "/frend/", "朋友"),
            ],
            "Unit 3 Fun in the kitchen": [
                w("carrot", "/ˈkærət/", "胡萝卜"),
                w("pea", "/piː/", "豌豆"),
                w("pepper", "/ˈpepə/", "柿子椒"),
                w("onion", "/ˈʌnjən/", "洋葱"),
            ],
            "Unit 4 Spring": [
                w("tree", "/triː/", "树"),
                w("flower", "/ˈflaʊə/", "花"),
                w("beautiful", "/ˈbjuːtɪfl/", "美丽的"),
                w("bird", "/bɜːd/", "鸟"),
                w("kite", "/kaɪt/", "风筝"),
                w("spring", "/sprɪŋ/", "春天"),
                w("green", "/ɡriːn/", "绿色的"),
            ],
            "Unit 5 In the park": [
                w("cute", "/kjuːt/", "可爱的"),
                w("ladybird", "/ˈleɪdibɜːd/", "瓢虫"),
                w("butterfly", "/ˈbʌtəflaɪ/", "蝴蝶"),
                w("dragonfly", "/ˈdræɡənflaɪ/", "蜻蜓"),
                w("cicada", "/sɪˈkɑːdə/", "蝉"),
            ],
            "Unit 6 We are happy": [
                w("we", "/wiː/", "我们"),
                w("happy", "/ˈhæpi/", "开心的"),
                w("they", "/ðeɪ/", "他们/她们/它们"),
                w("all", "/ɔːl/", "全部"),
            ],
            "Unit 7 On the farm": [
                w("pig", "/pɪɡ/", "猪"),
                w("lamb", "/læm/", "小羊"),
                w("duck", "/dʌk/", "鸭子"),
                w("cow", "/kaʊ/", "奶牛"),
            ],
            "Unit 8 My little bag": [
                w("in", "/ɪn/", "在……里面"),
                w("bottle", "/ˈbɒtl/", "瓶子"),
                w("hankie", "/ˈhæŋki/", "手帕"),
            ],
        }
    },
    "二年级": {
        "上学期": {
            "Unit 1 My family": [
                w("aunt", "/ɑːnt/", "姑妈；阿姨"),
                w("cousin", "/ˈkʌzn/", "堂/表兄弟姐妹"),
                w("uncle", "/ˈʌŋkl/", "叔叔；伯伯"),
                w("tall", "/tɔːl/", "高的"),
                w("Mrs", "/ˈmɪsɪz/", "夫人"),
                w("short", "/ʃɔːt/", "矮的"),
            ],
            "Unit 2 My pet": [
                w("have", "/hæv/", "有"),
                w("rabbit", "/ˈræbɪt/", "兔子"),
                w("white", "/waɪt/", "白色的"),
                w("small", "/smɔːl/", "小的"),
                w("dog", "/dɒɡ/", "狗"),
                w("brown", "/braʊn/", "棕色的"),
                w("big", "/bɪɡ/", "大的"),
                w("hamster", "/ˈhæmstə/", "仓鼠"),
                w("cat", "/kæt/", "猫"),
            ],
            "Unit 3 At the zoo": [
                w("it", "/ɪt/", "它"),
                w("has", "/hæz/", "有"),
                w("short", "/ʃɔːt/", "短的"),
                w("tail", "/teɪl/", "尾巴"),
                w("bear", "/beə/", "熊"),
                w("giraffe", "/dʒɪˈrɑːf/", "长颈鹿"),
                w("long", "/lɒŋ/", "长的"),
                w("neck", "/nek/", "脖子"),
                w("monkey", "/ˈmʌŋki/", "猴子"),
                w("tiger", "/ˈtaɪɡə/", "老虎"),
            ],
            "Unit 4 In autumn": [
                w("autumn", "/ˈɔːtəm/", "秋天"),
                w("cool", "/kuːl/", "凉爽的"),
                w("apple", "/ˈæpl/", "苹果"),
                w("pear", "/peə/", "梨"),
                w("pumpkin", "/ˈpʌmpkɪn/", "南瓜"),
                w("orange", "/ˈɒrɪndʒ/", "橙子"),
                w("potato", "/pəˈteɪtəʊ/", "土豆"),
            ],
            "Unit 5 Have some juice": [
                w("have", "/hæv/", "吃；喝"),
                w("some", "/sʌm/", "一些"),
                w("juice", "/dʒuːs/", "果汁"),
                w("yogurt", "/ˈjɒɡət/", "酸奶"),
                w("snack", "/snæk/", "零食"),
                w("sandwich", "/ˈsænwɪtʃ/", "三明治"),
                w("yummy", "/ˈjʌmi/", "好吃的"),
                w("tart", "/tɑːt/", "果馅饼"),
                w("cupcake", "/ˈkʌpkeɪk/", "纸杯蛋糕"),
            ],
            "Unit 6 My clothes": [
                w("coat", "/kəʊt/", "外套"),
                w("scarf", "/skɑːf/", "围巾"),
                w("sweater", "/ˈswetə/", "毛衣"),
                w("shirt", "/ʃɜːt/", "衬衫"),
                w("T-shirt", "/ˈtiːʃɜːt/", "T恤衫"),
                w("dress", "/dres/", "连衣裙"),
                w("skirt", "/skɜːt/", "裙子"),
            ],
            "Unit 7 Clean up!": [
                w("clean", "/kliːn/", "打扫"),
                w("table", "/ˈteɪbl/", "桌子"),
                w("chair", "/tʃeə/", "椅子"),
                w("desk", "/desk/", "书桌"),
                w("door", "/dɔː/", "门"),
                w("window", "/ˈwɪndəʊ/", "窗户"),
            ],
            "Unit 8 Jobs": [
                w("doctor", "/ˈdɒktə/", "医生"),
                w("cook", "/kʊk/", "厨师"),
                w("teacher", "/ˈtiːtʃə/", "老师"),
                w("nurse", "/nɜːs/", "护士"),
                w("farmer", "/ˈfɑːmə/", "农民"),
                w("worker", "/ˈwɜːkə/", "工人"),
            ],
        },
        "下学期": {
            "Unit 1 Where's my…?": [
                w("on", "/ɒn/", "在……上面"),
                w("sofa", "/ˈsəʊfə/", "沙发"),
                w("under", "/ˈʌndə/", "在……下面"),
                w("behind", "/bɪˈhaɪnd/", "在……后面"),
                w("vase", "/vɑːz/", "花瓶"),
                w("basket", "/ˈbɑːskɪt/", "篮子"),
            ],
            "Unit 2 Dinner is ready!": [
                w("dinner", "/ˈdɪnə/", "晚餐；正餐"),
                w("ready", "/ˈredi/", "准备好的"),
                w("rice", "/raɪs/", "米饭"),
                w("broccoli", "/ˈbrɒkəli/", "西兰花"),
                w("fish", "/fɪʃ/", "鱼"),
                w("soup", "/suːp/", "汤"),
                w("meat", "/miːt/", "肉"),
                w("noodles", "/ˈnuːdlz/", "面条"),
            ],
            "Unit 3 My school subjects": [
                w("PE", "/ˌpiːˈiː/", "体育"),
                w("Maths", "/mæθs/", "数学"),
                w("Chinese", "/ˌtʃaɪˈniːz/", "语文"),
                w("English", "/ˈɪŋɡlɪʃ/", "英语"),
                w("today", "/təˈdeɪ/", "今天"),
                w("fun", "/fʌn/", "有趣的"),
                w("easy", "/ˈiːzi/", "简单的"),
                w("Art", "/ɑːt/", "美术"),
                w("Music", "/ˈmjuːzɪk/", "音乐"),
            ],
            "Unit 4 My body": [
                w("nose", "/nəʊz/", "鼻子"),
                w("mouth", "/maʊθ/", "嘴巴"),
                w("hair", "/heə/", "头发"),
                w("ear", "/ɪə/", "耳朵"),
                w("face", "/feɪs/", "脸"),
                w("eye", "/aɪ/", "眼睛"),
                w("big", "/bɪɡ/", "大的"),
                w("small", "/smɔːl/", "小的"),
                w("long", "/lɒŋ/", "长的"),
                w("short", "/ʃɔːt/", "短的"),
            ],
            "Unit 5 My favourite food": [
                w("like", "/laɪk/", "喜欢"),
                w("apple", "/ˈæpl/", "苹果"),
                w("banana", "/bəˈnɑːnə/", "香蕉"),
                w("orange", "/ˈɒrɪndʒ/", "橙子"),
                w("pear", "/peə/", "梨"),
                w("grape", "/ɡreɪp/", "葡萄"),
                w("watermelon", "/ˈwɔːtəmelən/", "西瓜"),
                w("strawberry", "/ˈstrɔːbəri/", "草莓"),
            ],
            "Unit 6 Let's go shopping!": [
                w("shop", "/ʃɒp/", "购物"),
                w("toy", "/tɔɪ/", "玩具"),
                w("doll", "/dɒl/", "玩具娃娃"),
                w("ball", "/bɔːl/", "球"),
                w("car", "/kɑː/", "小汽车"),
                w("kite", "/kaɪt/", "风筝"),
                w("robot", "/ˈrəʊbɒt/", "机器人"),
                w("bear", "/beə/", "熊"),
            ],
            "Unit 7 Happy birthday!": [
                w("birthday", "/ˈbɜːθdeɪ/", "生日"),
                w("cake", "/keɪk/", "蛋糕"),
                w("card", "/kɑːd/", "卡片"),
                w("present", "/ˈpreznt/", "礼物"),
                w("happy", "/ˈhæpi/", "开心的"),
                w("party", "/ˈpɑːti/", "聚会"),
                w("sing", "/sɪŋ/", "唱歌"),
                w("dance", "/dɑːns/", "跳舞"),
            ],
            "Unit 8 Seasons": [
                w("spring", "/sprɪŋ/", "春天"),
                w("warm", "/wɔːm/", "温暖的"),
                w("summer", "/ˈsʌmə/", "夏天"),
                w("hot", "/hɒt/", "热的"),
                w("autumn", "/ˈɔːtəm/", "秋天"),
                w("cool", "/kuːl/", "凉爽的"),
                w("winter", "/ˈwɪntə/", "冬天"),
                w("cold", "/kəʊld/", "冷的"),
            ],
        }
    },
    "三年级": {
        "上学期": {
            "Unit 1 Hello": [
                w("hello", "/həˈləʊ/", "你好"),
                w("hi", "/haɪ/", "你好"),
                w("I", "/aɪ/", "我"),
                w("am", "/æm/", "是"),
                w("Miss", "/mɪs/", "小姐"),
                w("good", "/ɡʊd/", "好的"),
                w("morning", "/ˈmɔːnɪŋ/", "早上"),
                w("afternoon", "/ˌɑːftəˈnuːn/", "下午"),
                w("class", "/klɑːs/", "同学们"),
                w("goodbye", "/ˌɡʊdˈbaɪ/", "再见"),
            ],
            "Unit 2 I'm Liu Tao": [
                w("are", "/ɑː/", "是"),
                w("you", "/juː/", "你"),
                w("yes", "/jes/", "是；对"),
                w("no", "/nəʊ/", "不；不是"),
                w("not", "/nɒt/", "不；没有"),
            ],
            "Unit 3 My friends": [
                w("my", "/maɪ/", "我的"),
                w("friend", "/frend/", "朋友"),
                w("she", "/ʃiː/", "她"),
                w("he", "/hiː/", "他"),
                w("too", "/tuː/", "也"),
                w("this", "/ðɪs/", "这；这个"),
                w("is", "/ɪz/", "是"),
                w("sister", "/ˈsɪstə/", "姐姐；妹妹"),
            ],
            "Unit 4 My family": [
                w("family", "/ˈfæməli/", "家庭"),
                w("father", "/ˈfɑːðə/", "爸爸"),
                w("mother", "/ˈmʌðə/", "妈妈"),
                w("brother", "/ˈbrʌðə/", "哥哥；弟弟"),
                w("me", "/miː/", "我（宾格）"),
                w("grandpa", "/ˈɡrænpɑː/", "爷爷；外公"),
                w("grandma", "/ˈɡrænmɑː/", "奶奶；外婆"),
                w("evening", "/ˈiːvnɪŋ/", "晚上"),
            ],
            "Unit 5 Look at me!": [
                w("look", "/lʊk/", "看"),
                w("at", "/æt/", "在"),
                w("cap", "/kæp/", "帽子"),
                w("T-shirt", "/ˈtiːʃɜːt/", "T恤衫"),
                w("skirt", "/skɜːt/", "裙子"),
                w("nice", "/naɪs/", "好看的"),
                w("great", "/ɡreɪt/", "很好的"),
            ],
            "Unit 6 Colours": [
                w("colour", "/ˈkʌlə/", "颜色"),
                w("red", "/red/", "红色"),
                w("green", "/ɡriːn/", "绿色"),
                w("yellow", "/ˈjeləʊ/", "黄色"),
                w("blue", "/bluː/", "蓝色"),
                w("orange", "/ˈɒrɪndʒ/", "橙色；橙子"),
                w("black", "/blæk/", "黑色"),
                w("white", "/waɪt/", "白色"),
            ],
            "Unit 7 Would you like…?": [
                w("a", "/ə/", "一（个）"),
                w("an", "/æn/", "一（个）"),
                w("egg", "/eɡ/", "蛋"),
                w("cake", "/keɪk/", "蛋糕"),
                w("pie", "/paɪ/", "馅饼"),
                w("sweet", "/swiːt/", "糖果"),
                w("hot dog", "/ˈhɒt dɒɡ/", "热狗"),
                w("what", "/wɒt/", "什么"),
            ],
            "Unit 8 Happy New Year!": [
                w("happy", "/ˈhæpi/", "开心的"),
                w("New Year", "/njuː jɪə/", "新年"),
                w("doll", "/dɒl/", "玩具娃娃"),
                w("ball", "/bɔːl/", "球"),
                w("robot", "/ˈrəʊbɒt/", "机器人"),
                w("car", "/kɑː/", "小汽车"),
                w("toy", "/tɔɪ/", "玩具"),
            ],
        },
        "下学期": {
            "Unit 1 In class": [
                w("open", "/ˈəʊpən/", "打开"),
                w("the", "/ðə/", "这；那"),
                w("door", "/dɔː/", "门"),
                w("close", "/kləʊz/", "关闭"),
                w("window", "/ˈwɪndəʊ/", "窗户"),
                w("book", "/bʊk/", "书"),
                w("rubber", "/ˈrʌbə/", "橡皮"),
                w("ruler", "/ˈruːlə/", "尺"),
                w("pencil", "/ˈpensl/", "铅笔"),
                w("pen", "/pen/", "钢笔"),
                w("crayon", "/ˈkreɪən/", "蜡笔"),
                w("pencil case", "/ˈpensl keɪs/", "铅笔盒"),
            ],
            "Unit 2 In the library": [
                w("in", "/ɪn/", "在……里"),
                w("run", "/rʌn/", "跑"),
                w("eat", "/iːt/", "吃"),
                w("talk", "/tɔːk/", "说话"),
                w("here", "/hɪə/", "这里"),
                w("sleep", "/sliːp/", "睡觉"),
                w("drink", "/drɪŋk/", "喝"),
            ],
            "Unit 3 Is this your pencil?": [
                w("your", "/jɔː/", "你的"),
                w("pencil", "/ˈpensl/", "铅笔"),
                w("schoolbag", "/ˈskuːlbæɡ/", "书包"),
                w("pen", "/pen/", "钢笔"),
                w("crayon", "/ˈkreɪən/", "蜡笔"),
                w("ruler", "/ˈruːlə/", "尺"),
                w("pencil case", "/ˈpensl keɪs/", "铅笔盒"),
                w("lunch box", "/ˈlʌntʃ bɒks/", "午餐盒"),
                w("where", "/weə/", "在哪里"),
                w("over there", "/ˈəʊvə ðeə/", "在那里"),
            ],
            "Unit 4 Where's the bird?": [
                w("bird", "/bɜːd/", "鸟"),
                w("beautiful", "/ˈbjuːtɪfl/", "漂亮的"),
                w("under", "/ˈʌndə/", "在……下面"),
                w("desk", "/desk/", "课桌"),
                w("behind", "/bɪˈhaɪnd/", "在……后面"),
                w("on", "/ɒn/", "在……上面"),
                w("chair", "/tʃeə/", "椅子"),
                w("tree", "/triː/", "树"),
                w("guess", "/ɡes/", "猜"),
            ],
            "Unit 5 How old are you?": [
                w("one", "/wʌn/", "一"),
                w("two", "/tuː/", "二"),
                w("three", "/θriː/", "三"),
                w("four", "/fɔː/", "四"),
                w("five", "/faɪv/", "五"),
                w("six", "/sɪks/", "六"),
                w("seven", "/ˈsevn/", "七"),
                w("eight", "/eɪt/", "八"),
                w("nine", "/naɪn/", "九"),
                w("ten", "/ten/", "十"),
                w("old", "/əʊld/", "……岁的"),
                w("how old", "/haʊ əʊld/", "多大"),
                w("lovely", "/ˈlʌvli/", "可爱的"),
            ],
            "Unit 6 What time is it?": [
                w("time", "/taɪm/", "时间"),
                w("o'clock", "/əˈklɒk/", "……点钟"),
                w("breakfast", "/ˈbrekfəst/", "早餐"),
                w("class", "/klɑːs/", "课"),
                w("lunch", "/lʌntʃ/", "午餐"),
                w("eleven", "/ɪˈlevn/", "十一"),
                w("twelve", "/twelv/", "十二"),
                w("wake up", "/weɪk ʌp/", "醒"),
                w("hurry up", "/ˈhʌri ʌp/", "快点"),
            ],
            "Unit 7 On the farm": [
                w("farm", "/fɑːm/", "农场"),
                w("they", "/ðeɪ/", "他们；她们；它们"),
                w("pig", "/pɪɡ/", "猪"),
                w("cow", "/kaʊ/", "奶牛"),
                w("chicken", "/ˈtʃɪkɪn/", "鸡"),
                w("duck", "/dʌk/", "鸭子"),
                w("pear", "/peə/", "梨"),
                w("apple", "/ˈæpl/", "苹果"),
                w("orange", "/ˈɒrɪndʒ/", "橙子"),
                w("who", "/huː/", "谁"),
            ],
            "Unit 8 We're twins!": [
                w("we", "/wiː/", "我们"),
                w("twin", "/twɪn/", "双胞胎之一"),
                w("aunt", "/ɑːnt/", "姑妈；阿姨"),
                w("girl", "/ɡɜːl/", "女孩"),
                w("man", "/mæn/", "男人"),
                w("woman", "/ˈwʊmən/", "女人"),
                w("boy", "/bɔɪ/", "男孩"),
                w("baby", "/ˈbeɪbi/", "婴儿"),
                w("cousin", "/ˈkʌzn/", "堂/表兄弟姐妹"),
            ],
        }
    },
    "四年级": {
        "上学期": {
            "Unit 1 Our school subjects": [
                w("subject", "/ˈsʌbdʒɪkt/", "学科"),
                w("Chinese", "/ˌtʃaɪˈniːz/", "语文"),
                w("English", "/ˈɪŋɡlɪʃ/", "英语"),
                w("Maths", "/mæθs/", "数学"),
                w("PE", "/ˌpiːˈiː/", "体育"),
                w("Art", "/ɑːt/", "美术"),
                w("Music", "/ˈmjuːzɪk/", "音乐"),
                w("lesson", "/ˈlesn/", "课"),
                w("Monday", "/ˈmʌndeɪ/", "星期一"),
            ],
            "Unit 2 After school": [
                w("go", "/ɡəʊ/", "去"),
                w("go to school", "/ɡəʊ tə skuːl/", "上学"),
                w("get up", "/ɡet ʌp/", "起床"),
                w("have breakfast", "/hæv ˈbrekfəst/", "吃早饭"),
                w("have lunch", "/hæv lʌntʃ/", "吃午饭"),
                w("have dinner", "/hæv ˈdɪnə/", "吃晚饭"),
                w("go home", "/ɡəʊ həʊm/", "回家"),
                w("go to bed", "/ɡəʊ tə bed/", "睡觉"),
                w("watch TV", "/wɒtʃ ˌtiːˈviː/", "看电视"),
                w("in the morning", "/ɪn ðə ˈmɔːnɪŋ/", "在上午"),
                w("in the afternoon", "/ɪn ðə ˌɑːftəˈnuːn/", "在下午"),
                w("in the evening", "/ɪn ðə ˈiːvnɪŋ/", "在晚上"),
                w("at night", "/æt naɪt/", "在夜里"),
            ],
            "Unit 3 How many?": [
                w("one", "/wʌn/", "一"),
                w("two", "/tuː/", "二"),
                w("three", "/θriː/", "三"),
                w("four", "/fɔː/", "四"),
                w("five", "/faɪv/", "五"),
                w("six", "/sɪks/", "六"),
                w("seven", "/ˈsevn/", "七"),
                w("eight", "/eɪt/", "八"),
                w("nine", "/naɪn/", "九"),
                w("ten", "/ten/", "十"),
                w("eleven", "/ɪˈlevn/", "十一"),
                w("twelve", "/twelv/", "十二"),
                w("thirteen", "/ˌθɜːˈtiːn/", "十三"),
                w("fourteen", "/ˌfɔːˈtiːn/", "十四"),
                w("fifteen", "/ˌfɪfˈtiːn/", "十五"),
                w("sixteen", "/ˌsɪksˈtiːn/", "十六"),
                w("seventeen", "/ˌsevnˈtiːn/", "十七"),
                w("eighteen", "/ˌeɪˈtiːn/", "十八"),
                w("nineteen", "/ˌnaɪnˈtiːn/", "十九"),
                w("twenty", "/ˈtwenti/", "二十"),
                w("sticker", "/ˈstɪkə/", "贴纸"),
                w("can", "/kæn/", "可以；能"),
                w("very", "/ˈveri/", "很"),
            ],
            "Unit 4 I can play basketball": [
                w("basketball", "/ˈbɑːskɪtbɔːl/", "篮球"),
                w("well", "/wel/", "好"),
                w("have a try", "/hæv ə traɪ/", "试一试"),
                w("football", "/ˈfʊtbɔːl/", "足球"),
                w("jump", "/dʒʌmp/", "跳"),
                w("skate", "/skeɪt/", "滑冰"),
                w("swim", "/swɪm/", "游泳"),
                w("fly", "/flaɪ/", "飞"),
                w("sad", "/sæd/", "难过的"),
            ],
            "Unit 5 Our new home": [
                w("home", "/həʊm/", "家"),
                w("bedroom", "/ˈbedruːm/", "卧室"),
                w("living room", "/ˈlɪvɪŋ ruːm/", "客厅"),
                w("sofa", "/ˈsəʊfə/", "沙发"),
                w("table", "/ˈteɪbl/", "桌子"),
                w("fridge", "/frɪdʒ/", "冰箱"),
                w("clock", "/klɒk/", "钟"),
                w("bathroom", "/ˈbɑːθruːm/", "浴室"),
                w("kitchen", "/ˈkɪtʃɪn/", "厨房"),
                w("hungry", "/ˈhʌŋɡri/", "饿的"),
                w("find", "/faɪnd/", "找到"),
                w("come", "/kʌm/", "来"),
            ],
            "Unit 6 At the snack bar": [
                w("snack bar", "/ˈsnæk bɑː/", "快餐店"),
                w("coffee", "/ˈkɒfi/", "咖啡"),
                w("tea", "/tiː/", "茶"),
                w("juice", "/dʒuːs/", "果汁"),
                w("rice", "/raɪs/", "米饭"),
                w("fish", "/fɪʃ/", "鱼"),
                w("hamburger", "/ˈhæmbɜːɡə/", "汉堡包"),
                w("sandwich", "/ˈsænwɪtʃ/", "三明治"),
                w("noodles", "/ˈnuːdlz/", "面条"),
                w("milk", "/mɪlk/", "牛奶"),
                w("glass", "/ɡlɑːs/", "玻璃杯"),
                w("cup", "/kʌp/", "杯子"),
            ],
            "Unit 7 How much?": [
                w("how much", "/haʊ mʌtʃ/", "多少钱"),
                w("shoe", "/ʃuː/", "鞋"),
                w("sock", "/sɒk/", "袜子"),
                w("twenty", "/ˈtwenti/", "二十"),
                w("thirty", "/ˈθɜːti/", "三十"),
                w("forty", "/ˈfɔːti/", "四十"),
                w("fifty", "/ˈfɪfti/", "五十"),
                w("sixty", "/ˈsɪksti/", "六十"),
                w("seventy", "/ˈsevnti/", "七十"),
                w("eighty", "/ˈeɪti/", "八十"),
                w("ninety", "/ˈnaɪnti/", "九十"),
                w("hundred", "/ˈhʌndrəd/", "一百"),
                w("fan", "/fæn/", "扇子"),
                w("umbrella", "/ʌmˈbrelə/", "伞"),
                w("long", "/lɒŋ/", "长的"),
                w("short", "/ʃɔːt/", "短的；矮的"),
            ],
            "Unit 8 Doll": [
                w("doll", "/dɒl/", "玩具娃娃"),
                w("hair", "/heə/", "头发"),
                w("eye", "/aɪ/", "眼睛"),
                w("nose", "/nəʊz/", "鼻子"),
                w("mouth", "/maʊθ/", "嘴"),
                w("ear", "/ɪə/", "耳朵"),
                w("thin", "/θɪn/", "瘦的"),
                w("tall", "/tɔːl/", "高的"),
                w("short", "/ʃɔːt/", "矮的"),
                w("beautiful", "/ˈbjuːtɪfl/", "漂亮的"),
                w("lovely", "/ˈlʌvli/", "可爱的"),
                w("big", "/bɪɡ/", "大的"),
                w("small", "/smɔːl/", "小的"),
            ],
        },
        "下学期": {
            "Unit 1 We're friends": [
                w("weak", "/wiːk/", "虚弱的"),
                w("strong", "/strɒŋ/", "强壮的"),
                w("become", "/bɪˈkʌm/", "变成"),
                w("from", "/frɒm/", "从"),
                w("party", "/ˈpɑːti/", "聚会"),
                w("friendship", "/ˈfrendʃɪp/", "友谊"),
                w("forest", "/ˈfɒrɪst/", "森林"),
                w("thin", "/θɪn/", "瘦的"),
                w("one day", "/wʌn deɪ/", "有一天"),
                w("angry", "/ˈæŋɡri/", "生气的"),
                w("net", "/net/", "网"),
                w("sad", "/sæd/", "难过的"),
                w("hole", "/həʊl/", "洞"),
                w("help", "/help/", "帮助"),
            ],
            "Unit 2 Helping others at school": [
                w("help", "/help/", "帮助"),
                w("clean", "/kliːn/", "打扫；干净的"),
                w("classroom", "/ˈklɑːsruːm/", "教室"),
                w("window", "/ˈwɪndəʊ/", "窗户"),
                w("blackboard", "/ˈblækbɔːd/", "黑板"),
                w("chair", "/tʃeə/", "椅子"),
                w("desk", "/desk/", "课桌"),
                w("floor", "/flɔː/", "地面"),
                w("carry", "/ˈkæri/", "搬；拿"),
                w("heavy", "/ˈhevi/", "重的"),
                w("easy", "/ˈiːzi/", "容易的"),
                w("difficult", "/ˈdɪfɪkəlt/", "困难的"),
                w("kind", "/kaɪnd/", "友好的"),
                w("share", "/ʃeə/", "分享"),
            ],
            "Unit 3 Road safety": [
                w("road", "/rəʊd/", "马路"),
                w("safety", "/ˈseɪfti/", "安全"),
                w("cross", "/krɒs/", "穿过"),
                w("safe", "/seɪf/", "安全的"),
                w("must", "/mʌst/", "必须"),
                w("zebra crossing", "/ˈziːbrə ˈkrɒsɪŋ/", "斑马线"),
                w("pavement", "/ˈpeɪvmənt/", "人行道"),
                w("look out for", "/lʊk aʊt fɔː/", "当心"),
                w("follow", "/ˈfɒləʊ/", "遵守"),
                w("rule", "/ruːl/", "规则"),
                w("stay", "/steɪ/", "保持"),
            ],
            "Unit 4 Caring about others": [
                w("care", "/keə/", "关心"),
                w("ill", "/ɪl/", "生病的"),
                w("cold", "/kəʊld/", "感冒"),
                w("fever", "/ˈfiːvə/", "发烧"),
                w("headache", "/ˈhedeɪk/", "头疼"),
                w("cough", "/kɒf/", "咳嗽"),
                w("wrong", "/rɒŋ/", "错误的"),
                w("worried", "/ˈwʌrɪd/", "担心的"),
                w("sad", "/sæd/", "难过的"),
                w("happy", "/ˈhæpi/", "开心的"),
                w("sorry", "/ˈsɒri/", "对不起"),
                w("angry", "/ˈæŋɡri/", "生气的"),
            ],
            "Unit 5 Eating out": [
                w("restaurant", "/ˈrestrɒnt/", "饭店"),
                w("menu", "/ˈmenjuː/", "菜单"),
                w("food", "/fuːd/", "食物"),
                w("noodle", "/ˈnuːdl/", "面条"),
                w("rice", "/raɪs/", "米饭"),
                w("soup", "/suːp/", "汤"),
                w("vegetable", "/ˈvedʒtəbl/", "蔬菜"),
                w("meat", "/miːt/", "肉"),
                w("chicken", "/ˈtʃɪkɪn/", "鸡肉"),
                w("fish", "/fɪʃ/", "鱼"),
                w("beef", "/biːf/", "牛肉"),
                w("potato", "/pəˈteɪtəʊ/", "土豆"),
                w("tomato", "/təˈmɑːtəʊ/", "西红柿"),
                w("delicious", "/dɪˈlɪʃəs/", "美味的"),
            ],
            "Unit 6 Jobs": [
                w("job", "/dʒɒb/", "工作"),
                w("teacher", "/ˈtiːtʃə/", "老师"),
                w("doctor", "/ˈdɒktə/", "医生"),
                w("nurse", "/nɜːs/", "护士"),
                w("cook", "/kʊk/", "厨师"),
                w("driver", "/ˈdraɪvə/", "司机"),
                w("farmer", "/ˈfɑːmə/", "农民"),
                w("worker", "/ˈwɜːkə/", "工人"),
                w("policeman", "/pəˈliːsmən/", "警察"),
                w("fireman", "/ˈfaɪəmən/", "消防员"),
                w("want", "/wɒnt/", "想要"),
                w("be good at", "/biː ɡʊd æt/", "擅长"),
            ],
            "Unit 7 Doing chores at home": [
                w("chore", "/tʃɔː/", "家务"),
                w("sweep", "/swiːp/", "扫"),
                w("floor", "/flɔː/", "地面"),
                w("clean", "/kliːn/", "打扫"),
                w("wash", "/wɒʃ/", "洗"),
                w("dish", "/dɪʃ/", "盘子"),
                w("make", "/meɪk/", "整理"),
                w("bed", "/bed/", "床"),
                w("water", "/ˈwɔːtə/", "浇水"),
                w("plant", "/plɑːnt/", "植物"),
                w("cook", "/kʊk/", "烹饪"),
                w("meal", "/miːl/", "一餐"),
                w("helpful", "/ˈhelpfl/", "有帮助的"),
                w("lazy", "/ˈleɪzi/", "懒惰的"),
            ],
            "Unit 8 In the kitchen": [
                w("kitchen", "/ˈkɪtʃɪn/", "厨房"),
                w("fridge", "/frɪdʒ/", "冰箱"),
                w("egg", "/eɡ/", "蛋"),
                w("bread", "/bred/", "面包"),
                w("milk", "/mɪlk/", "牛奶"),
                w("juice", "/dʒuːs/", "果汁"),
                w("butter", "/ˈbʌtə/", "黄油"),
                w("salt", "/sɔːlt/", "盐"),
                w("sugar", "/ˈʃʊɡə/", "糖"),
                w("knife", "/naɪf/", "刀"),
                w("fork", "/fɔːk/", "叉子"),
                w("spoon", "/spuːn/", "勺子"),
                w("chopsticks", "/ˈtʃɒpstɪks/", "筷子"),
                w("hungry", "/ˈhʌŋɡri/", "饿的"),
                w("full", "/fʊl/", "饱的"),
            ],
        }
    },
    "五年级": {
        "上学期": {
            "Unit 1 Goldilocks and the three bears": [
                w("bear", "/beə/", "熊"),
                w("forest", "/ˈfɒrɪst/", "森林"),
                w("house", "/haʊs/", "房子"),
                w("soup", "/suːp/", "汤"),
                w("just right", "/dʒʌst raɪt/", "正合适"),
                w("room", "/ruːm/", "房间"),
                w("hard", "/hɑːd/", "硬的"),
                w("soft", "/sɒft/", "软的"),
                w("afraid", "/əˈfreɪd/", "害怕的"),
                w("in front of", "/ɪn frʌnt əv/", "在……前面"),
                w("beside", "/bɪˈsaɪd/", "在……旁边"),
                w("between", "/bɪˈtwiːn/", "在……中间"),
                w("really", "/ˈriːəli/", "真的"),
                w("find", "/faɪnd/", "找到"),
                w("their", "/ðeə/", "他们的"),
            ],
            "Unit 2 A new student": [
                w("student", "/ˈstjuːdnt/", "学生"),
                w("classroom", "/ˈklɑːsruːm/", "教室"),
                w("second", "/ˈsekənd/", "第二"),
                w("floor", "/flɔː/", "楼层"),
                w("computer", "/kəmˈpjuːtə/", "电脑"),
                w("third", "/θɜːd/", "第三"),
                w("first", "/fɜːst/", "第一"),
                w("swing", "/swɪŋ/", "秋千"),
                w("push", "/pʊʃ/", "推"),
                w("heavy", "/ˈhevi/", "重的"),
                w("stop", "/stɒp/", "停止"),
                w("high", "/haɪ/", "高的"),
                w("great", "/ɡreɪt/", "很好的"),
            ],
            "Unit 3 Our animal friends": [
                w("animal", "/ˈænɪml/", "动物"),
                w("friend", "/frend/", "朋友"),
                w("leg", "/leɡ/", "腿"),
                w("arm", "/ɑːm/", "手臂"),
                w("body", "/ˈbɒdi/", "身体"),
                w("or", "/ɔː/", "也不"),
                w("other", "/ˈʌðə/", "其他的"),
                w("finger", "/ˈfɪŋɡə/", "手指"),
                w("tail", "/teɪl/", "尾巴"),
                w("wing", "/wɪŋ/", "翅膀"),
                w("foot", "/fʊt/", "脚（复数 feet）"),
            ],
            "Unit 4 Hobbies": [
                w("hobby", "/ˈhɒbi/", "业余爱好"),
                w("be good at", "/biː ɡʊd æt/", "擅长"),
                w("read", "/riːd/", "读"),
                w("dance", "/dɑːns/", "跳舞"),
                w("sing", "/sɪŋ/", "唱歌"),
                w("swim", "/swɪm/", "游泳"),
                w("skate", "/skeɪt/", "滑冰"),
                w("jump", "/dʒʌmp/", "跳"),
                w("climb", "/klaɪm/", "爬"),
                w("run", "/rʌn/", "跑"),
                w("play", "/pleɪ/", "玩"),
                w("also", "/ˈɔːlsəʊ/", "也"),
                w("piano", "/piˈænəʊ/", "钢琴"),
                w("watch", "/wɒtʃ/", "看"),
                w("film", "/fɪlm/", "电影"),
                w("draw", "/drɔː/", "绘画"),
            ],
            "Unit 5 What do they do?": [
                w("teacher", "/ˈtiːtʃə/", "老师"),
                w("teach", "/tiːtʃ/", "教"),
                w("writer", "/ˈraɪtə/", "作家"),
                w("write", "/raɪt/", "写"),
                w("work", "/wɜːk/", "工作"),
                w("at home", "/æt həʊm/", "在家"),
                w("doctor", "/ˈdɒktə/", "医生"),
                w("help", "/help/", "帮助"),
                w("sick", "/sɪk/", "生病的"),
                w("people", "/ˈpiːpl/", "人们"),
                w("factory", "/ˈfæktri/", "工厂"),
                w("worker", "/ˈwɜːkə/", "工人"),
                w("cook", "/kʊk/", "厨师"),
                w("driver", "/ˈdraɪvə/", "司机"),
                w("farmer", "/ˈfɑːmə/", "农民"),
                w("nurse", "/nɜːs/", "护士"),
            ],
            "Unit 6 My e-friend": [
                w("wait", "/weɪt/", "等待"),
                w("send", "/send/", "发送"),
                w("email", "/ˈiːmeɪl/", "电子邮件"),
                w("live", "/lɪv/", "住"),
                w("UK", "/juː ˈkeɪ/", "英国"),
                w("study", "/ˈstʌdi/", "学习"),
                w("Australia", "/ɒˈstreɪliə/", "澳大利亚"),
                w("Canada", "/ˈkænədə/", "加拿大"),
                w("China", "/ˈtʃaɪnə/", "中国"),
                w("US", "/juː ˈes/", "美国"),
                w("go fishing", "/ɡəʊ ˈfɪʃɪŋ/", "去钓鱼"),
                w("tomorrow", "/təˈmɒrəʊ/", "明天"),
                w("don't worry", "/dəʊnt ˈwʌri/", "别担心"),
            ],
            "Unit 7 At weekends": [
                w("weekend", "/ˈwiːkˌend/", "周末"),
                w("visit", "/ˈvɪzɪt/", "探访"),
                w("grandparent", "/ˈɡrænpeərənt/", "祖父母"),
                w("play", "/pleɪ/", "玩"),
                w("often", "/ˈɒfn/", "经常"),
                w("chat", "/tʃæt/", "聊天"),
                w("Internet", "/ˈɪntənet/", "互联网"),
                w("always", "/ˈɔːlweɪz/", "总是"),
                w("sometimes", "/ˈsʌmtaɪmz/", "有时"),
                w("go to the cinema", "/ɡəʊ tə ðə ˈsɪnəmə/", "看电影"),
                w("a lot", "/ə lɒt/", "很多"),
            ],
            "Unit 8 At Christmas": [
                w("Christmas", "/ˈkrɪsməs/", "圣诞节"),
                w("buy", "/baɪ/", "买"),
                w("present", "/ˈpreznt/", "礼物"),
                w("Christmas tree", "/ˈkrɪsməs triː/", "圣诞树"),
                w("Father Christmas", "/ˈfɑːðə ˈkrɪsməs/", "圣诞老人"),
                w("next", "/nekst/", "来的"),
                w("put", "/pʊt/", "放"),
                w("pretty", "/ˈprɪti/", "漂亮的"),
                w("Christmas Eve", "/ˈkrɪsməs iːv/", "平安夜"),
                w("stocking", "/ˈstɒkɪŋ/", "长统袜"),
                w("wait for", "/weɪt fɔː/", "等待"),
                w("finally", "/ˈfaɪnəli/", "最后"),
                w("Christmas Day", "/ˈkrɪsməs deɪ/", "圣诞节"),
                w("turkey", "/ˈtɜːki/", "火鸡"),
                w("pudding", "/ˈpʊdɪŋ/", "布丁"),
                w("have a good time", "/hæv ə ɡʊd taɪm/", "过得愉快"),
            ],
        },
        "下学期": {
            "Unit 1 Cinderella": [
                w("prince", "/prɪns/", "王子"),
                w("fairy", "/ˈfeəri/", "仙女"),
                w("why", "/waɪ/", "为什么"),
                w("because", "/bɪˈkɒz/", "因为"),
                w("clothes", "/kləʊðz/", "衣服"),
                w("let", "/let/", "让"),
                w("put on", "/pʊt ɒn/", "穿上"),
                w("before", "/bɪˈfɔː/", "在……以前"),
                w("have to", "/hæv tuː/", "不得不"),
                w("try on", "/traɪ ɒn/", "试穿"),
                w("fit", "/fɪt/", "合适"),
                w("take off", "/teɪk ɒf/", "脱下"),
                w("late", "/leɪt/", "迟的"),
                w("pick", "/pɪk/", "摘"),
                w("understand", "/ˌʌndəˈstænd/", "明白"),
            ],
            "Unit 2 How do you come to school?": [
                w("far from", "/fɑː frɒm/", "离……远"),
                w("street", "/striːt/", "街道"),
                w("near", "/nɪə/", "在……附近"),
                w("city", "/ˈsɪti/", "城市"),
                w("bus", "/bʌs/", "公共汽车"),
                w("on foot", "/ɒn fʊt/", "步行"),
                w("metro", "/ˈmetrəʊ/", "地铁"),
                w("taxi", "/ˈtæksi/", "出租车"),
                w("bike", "/baɪk/", "自行车"),
                w("plane", "/pleɪn/", "飞机"),
                w("ship", "/ʃɪp/", "船"),
                w("train", "/treɪn/", "火车"),
                w("ride", "/raɪd/", "骑"),
            ],
            "Unit 3 Asking the way": [
                w("ask the way", "/ɑːsk ðə weɪ/", "问路"),
                w("get to", "/ɡet tuː/", "到达"),
                w("get on", "/ɡet ɒn/", "上车"),
                w("station", "/ˈsteɪʃn/", "车站"),
                w("get off", "/ɡet ɒf/", "下车"),
                w("walk", "/wɔːk/", "步行"),
                w("bookshop", "/ˈbʊkʃɒp/", "书店"),
                w("next to", "/nekst tuː/", "在……旁边"),
                w("excuse me", "/ɪkˈskjuːz miː/", "打扰"),
                w("along", "/əˈlɒŋ/", "沿着"),
                w("turn right", "/tɜːn raɪt/", "向右转"),
                w("traffic light", "/ˈtræfɪk laɪt/", "交通灯"),
                w("on your right", "/ɒn jɔː raɪt/", "在你右侧"),
            ],
            "Unit 4 Seeing the doctor": [
                w("see the doctor", "/siː ðə ˈdɒktə/", "看医生"),
                w("feel", "/fiːl/", "感觉"),
                w("check", "/tʃek/", "检查"),
                w("should", "/ʃʊd/", "应该"),
                w("have a rest", "/hæv ə rest/", "休息"),
                w("take medicine", "/teɪk ˈmedɪsɪn/", "吃药"),
                w("drink water", "/drɪŋk ˈwɔːtə/", "喝水"),
                w("toothache", "/ˈtuːθeɪk/", "牙疼"),
                w("dentist", "/ˈdentɪst/", "牙医"),
                w("brush one's teeth", "/brʌʃ wʌnz tiːθ/", "刷牙"),
                w("giraffe", "/dʒɪˈrɑːf/", "长颈鹿"),
                w("neck", "/nek/", "脖子"),
            ],
            "Unit 5 Helping our parents": [
                w("parent", "/ˈpeərənt/", "父；母"),
                w("clean", "/kliːn/", "打扫"),
                w("cook", "/kʊk/", "做"),
                w("wash", "/wɒʃ/", "洗"),
                w("sweep", "/swiːp/", "扫"),
                w("floor", "/flɔː/", "地面"),
                w("busy", "/ˈbɪzi/", "忙碌的"),
                w("wash the dishes", "/wɒʃ ðə ˈdɪʃɪz/", "洗碗"),
                w("make the bed", "/meɪk ðə bed/", "整理床铺"),
                w("grow", "/ɡrəʊ/", "种植"),
                w("garden", "/ˈɡɑːdn/", "花园"),
                w("pest", "/pest/", "害虫"),
                w("ladybird", "/ˈleɪdibɜːd/", "瓢虫"),
            ],
            "Unit 6 In the kitchen": [
                w("game", "/ɡeɪm/", "游戏"),
                w("smell", "/smel/", "闻起来"),
                w("meat", "/miːt/", "肉"),
                w("vegetable", "/ˈvedʒtəbl/", "蔬菜"),
                w("tomato", "/təˈmɑːtəʊ/", "西红柿"),
                w("potato", "/pəˈteɪtəʊ/", "土豆"),
                w("look for", "/lʊk fɔː/", "寻找"),
                w("ready", "/ˈredi/", "准备好"),
                w("yummy", "/ˈjʌmi/", "好吃的"),
                w("win", "/wɪn/", "赢得"),
                w("catch", "/kætʃ/", "抓住"),
            ],
            "Unit 7 Chinese festivals": [
                w("festival", "/ˈfestɪvl/", "节日"),
                w("Spring Festival", "/sprɪŋ ˈfestɪvl/", "春节"),
                w("January", "/ˈdʒænjuəri/", "一月"),
                w("February", "/ˈfebruəri/", "二月"),
                w("dumpling", "/ˈdʌmplɪŋ/", "饺子"),
                w("Dragon Boat Festival", "/ˈdræɡən bəʊt ˈfestɪvl/", "端午节"),
                w("May", "/meɪ/", "五月"),
                w("June", "/dʒuːn/", "六月"),
                w("rice dumpling", "/raɪs ˈdʌmplɪŋ/", "粽子"),
                w("Mid-Autumn Festival", "/mɪd ˈɔːtəm ˈfestɪvl/", "中秋节"),
                w("September", "/sepˈtembə/", "九月"),
                w("October", "/ɒkˈtəʊbə/", "十月"),
                w("moon cake", "/muːn keɪk/", "月饼"),
                w("Double Ninth Festival", "/ˈdʌbl naɪnθ ˈfestɪvl/", "重阳节"),
                w("mountain", "/ˈmaʊntɪn/", "山"),
            ],
            "Unit 8 Birthdays": [
                w("birthday", "/ˈbɜːθdeɪ/", "生日"),
                w("April", "/ˈeɪprəl/", "四月"),
                w("together", "/təˈɡeðə/", "一起"),
                w("game", "/ɡeɪm/", "游戏"),
                w("March", "/mɑːtʃ/", "三月"),
                w("July", "/dʒuˈlaɪ/", "七月"),
                w("August", "/ˈɔːɡəst/", "八月"),
                w("December", "/dɪˈsembə/", "十二月"),
                w("November", "/nəʊˈvembə/", "十一月"),
                w("answer", "/ˈɑːnsə/", "答案"),
                w("start", "/stɑːt/", "开始"),
            ],
        }
    },
    "六年级": {
        "上学期": {
            "Unit 1 The king's new clothes": [
                w("king", "/kɪŋ/", "国王"),
                w("new", "/njuː/", "新的"),
                w("story", "/ˈstɔːri/", "故事"),
                w("once upon a time", "/wʌns əˌpɒn ə taɪm/", "很久以前"),
                w("magic", "/ˈmædʒɪk/", "有魔力的"),
                w("clever", "/ˈklevə/", "聪明的"),
                w("foolish", "/ˈfuːlɪʃ/", "愚蠢的"),
                w("each", "/iːtʃ/", "每一个"),
                w("people", "/ˈpiːpl/", "人们"),
                w("shout", "/ʃaʊt/", "叫"),
                w("point at", "/pɔɪnt æt/", "指着"),
                w("laugh", "/lɑːf/", "笑"),
                w("wear", "/weə/", "穿"),
            ],
            "Unit 2 What a day!": [
                w("sunny", "/ˈsʌni/", "晴朗的"),
                w("interesting", "/ˈɪntrəstɪŋ/", "有趣的"),
                w("weather", "/ˈweðə/", "天气"),
                w("become", "/bɪˈkʌm/", "变成"),
                w("windy", "/ˈwɪndi/", "有风的"),
                w("cloudy", "/ˈklaʊdi/", "多云的"),
                w("sky", "/skaɪ/", "天空"),
                w("bring", "/brɪŋ/", "带来"),
                w("rainy", "/ˈreɪni/", "下雨的"),
                w("meet", "/miːt/", "遇见"),
                w("lose", "/luːz/", "丢失"),
                w("know", "/nəʊ/", "知道"),
            ],
            "Unit 3 Holiday fun": [
                w("holiday", "/ˈhɒlɪdeɪ/", "假期"),
                w("call", "/kɔːl/", "打电话"),
                w("Bund", "/bʌnd/", "外滩"),
                w("Shanghai Museum", "/ʃæŋˈhaɪ mjuːˈziːəm/", "上海博物馆"),
                w("Palace Museum", "/ˈpælɪs mjuːˈziːəm/", "故宫"),
                w("Summer Palace", "/ˈsʌmə ˈpælɪs/", "颐和园"),
                w("Tian'anmen Square", "/tjænˈænmən skweə/", "天安门广场"),
                w("great", "/ɡreɪt/", "很好的"),
                w("wear", "/weə/", "穿"),
                w("paper", "/ˈpeɪpə/", "纸"),
                w("ask", "/ɑːsk/", "问"),
            ],
            "Unit 4 Then and now": [
                w("then", "/ðen/", "那时"),
                w("now", "/naʊ/", "现在"),
                w("office", "/ˈɒfɪs/", "办公室"),
                w("newspaper", "/ˈnjuːzpeɪpə/", "报纸"),
                w("news", "/njuːz/", "新闻"),
                w("e-book", "/ˈiːbʊk/", "电子书"),
                w("make", "/meɪk/", "制作"),
                w("send", "/send/", "发送"),
                w("email", "/ˈiːmeɪl/", "电子邮件"),
                w("all over the world", "/ɔːl ˈəʊvə ðə wɜːld/", "全世界"),
                w("spell", "/spel/", "拼写"),
                w("do shopping", "/duː ˈʃɒpɪŋ/", "购物"),
            ],
            "Unit 5 Signs": [
                w("sign", "/saɪn/", "标志"),
                w("shopping centre", "/ˈʃɒpɪŋ ˈsentə/", "购物中心"),
                w("mean", "/miːn/", "意思是"),
                w("floor", "/flɔː/", "地面"),
                w("litter", "/ˈlɪtə/", "乱扔垃圾"),
                w("go in", "/ɡəʊ ɪn/", "进入"),
                w("take", "/teɪk/", "携带"),
                w("walk", "/wɔːk/", "走路"),
                w("restaurant", "/ˈrestrɒnt/", "饭店"),
                w("someone", "/ˈsʌmwʌn/", "某人"),
                w("smoke", "/sməʊk/", "吸烟"),
                w("danger", "/ˈdeɪndʒə/", "危险"),
                w("safe", "/seɪf/", "安全的"),
            ],
            "Unit 6 Keep our city clean": [
                w("keep", "/kiːp/", "保持"),
                w("city", "/ˈsɪti/", "城市"),
                w("clean", "/kliːn/", "干净的"),
                w("dirty", "/ˈdɜːti/", "脏的"),
                w("air", "/eə/", "空气"),
                w("smoke", "/sməʊk/", "烟雾"),
                w("rubbish", "/ˈrʌbɪʃ/", "垃圾"),
                w("messy", "/ˈmesi/", "乱的"),
                w("bin", "/bɪn/", "垃圾桶"),
                w("plant", "/plɑːnt/", "种植"),
                w("museum", "/mjuːˈziːəm/", "博物馆"),
                w("throw", "/θrəʊ/", "扔"),
                w("slip", "/slɪp/", "滑倒"),
                w("fall", "/fɔːl/", "摔倒"),
            ],
            "Unit 7 Protect the Earth": [
                w("protect", "/prəˈtekt/", "保护"),
                w("Earth", "/ɜːθ/", "地球"),
                w("save", "/seɪv/", "节约"),
                w("useful", "/ˈjuːsfl/", "有用的"),
                w("waste", "/weɪst/", "浪费"),
                w("reuse", "/ˌriːˈjuːz/", "再利用"),
                w("energy", "/ˈenədʒi/", "能源"),
                w("come from", "/kʌm frɒm/", "来自"),
                w("coal", "/kəʊl/", "煤"),
                w("oil", "/ɔɪl/", "石油"),
                w("cut down", "/kʌt daʊn/", "砍伐"),
                w("plastic", "/ˈplæstɪk/", "塑料"),
                w("glass", "/ɡlɑːs/", "玻璃"),
                w("paper", "/ˈpeɪpə/", "纸"),
            ],
            "Unit 8 Chinese New Year": [
                w("Chinese New Year", "/ˌtʃaɪˈniːz njuː jɪə/", "春节"),
                w("get", "/ɡet/", "收到"),
                w("red packet", "/red ˈpækɪt/", "红包"),
                w("plan", "/plæn/", "计划"),
                w("have dinner", "/hæv ˈdɪnə/", "吃年夜饭"),
                w("cook", "/kʊk/", "做"),
                w("food", "/fuːd/", "食物"),
                w("firecracker", "/ˈfaɪəˌkrækə/", "鞭炮"),
                w("fireworks", "/ˈfaɪəwɜːks/", "烟花"),
                w("watch", "/wɒtʃ/", "观看"),
                w("light", "/laɪt/", "点的"),
                w("excited", "/ɪkˈsaɪtɪd/", "激动的"),
                w("wonderful", "/ˈwʌndəfl/", "精彩的"),
            ],
        },
        "下学期": {
            "Unit 1 The lion and the mouse": [
                w("mouse", "/maʊs/", "老鼠"),
                w("large", "/lɑːdʒ/", "大的"),
                w("strong", "/strɒŋ/", "强壮的"),
                w("walk by", "/wɔːk baɪ/", "走过"),
                w("some day", "/sʌm deɪ/", "有一天"),
                w("quietly", "/ˈkwaɪətli/", "安静地"),
                w("weak", "/wiːk/", "弱的"),
                w("loudly", "/ˈlaʊdli/", "大声地"),
                w("the next day", "/ðə nekst deɪ/", "第二天"),
                w("net", "/net/", "网"),
                w("bite", "/baɪt/", "咬"),
                w("sharp", "/ʃɑːp/", "锋利的"),
                w("sadly", "/ˈsædli/", "难过地"),
                w("soon", "/suːn/", "不久"),
                w("happily", "/ˈhæpɪli/", "开心地"),
                w("from then on", "/frɒm ðen ɒn/", "从那时起"),
                w("quickly", "/ˈkwɪkli/", "迅速地"),
            ],
            "Unit 2 Good habits": [
                w("habit", "/ˈhæbɪt/", "习惯"),
                w("bad", "/bæd/", "不好的"),
                w("badly", "/ˈbædli/", "差地"),
                w("fast", "/fɑːst/", "快地"),
                w("finish", "/ˈfɪnɪʃ/", "完成"),
                w("last night", "/lɑːst naɪt/", "昨晚"),
                w("late", "/leɪt/", "迟"),
                w("tidy", "/ˈtaɪdi/", "整齐的"),
                w("messy", "/ˈmesi/", "乱的"),
                w("never", "/ˈnevə/", "从不"),
                w("sleepy", "/ˈsliːpi/", "困的"),
                w("slowly", "/ˈsləʊli/", "缓慢地"),
            ],
            "Unit 3 A healthy diet": [
                w("healthy", "/ˈhelθi/", "健康的"),
                w("diet", "/ˈdaɪət/", "饮食"),
                w("a little", "/ə ˈlɪtl/", "一点"),
                w("a few", "/ə fjuː/", "几个"),
                w("at a time", "/æt ə taɪm/", "一次"),
                w("cola", "/ˈkəʊlə/", "可乐"),
                w("need", "/niːd/", "需要"),
                w("food", "/fuːd/", "食物"),
            ],
            "Unit 4 Road safety": [
                w("road", "/rəʊd/", "马路"),
                w("safety", "/ˈseɪfti/", "安全"),
                w("cross", "/krɒs/", "穿过"),
                w("safe", "/seɪf/", "安全的"),
                w("must", "/mʌst/", "必须"),
                w("zebra crossing", "/ˈziːbrə ˈkrɒsɪŋ/", "斑马线"),
                w("pavement", "/ˈpeɪvmənt/", "人行道"),
                w("look out for", "/lʊk aʊt fɔː/", "当心"),
                w("follow", "/ˈfɒləʊ/", "遵守"),
                w("rule", "/ruːl/", "规则"),
                w("stay", "/steɪ/", "保持"),
            ],
            "Unit 5 A party": [
                w("child", "/tʃaɪld/", "孩子（复数 children）"),
                w("begin", "/bɪˈɡɪn/", "开始"),
                w("end", "/end/", "结束"),
                w("clown", "/klaʊn/", "小丑"),
                w("appear", "/əˈpɪə/", "出现"),
                w("balloon", "/bəˈluːn/", "气球"),
                w("put on", "/pʊt ɒn/", "上演"),
            ],
            "Unit 6 An interesting country": [
                w("country", "/ˈkʌntri/", "国家"),
                w("interesting", "/ˈɪntrəstɪŋ/", "有趣的"),
                w("Australia", "/ɒˈstreɪliə/", "澳大利亚"),
                w("kangaroo", "/ˌkæŋɡəˈruː/", "袋鼠"),
                w("koala", "/kəʊˈɑːlə/", "考拉"),
                w("sport", "/spɔːt/", "运动"),
                w("Sydney", "/ˈsɪdni/", "悉尼"),
                w("Big Ben", "/bɪɡ ben/", "大本钟"),
                w("London", "/ˈlʌndən/", "伦敦"),
                w("Oxford", "/ˈɒksfəd/", "牛津"),
                w("magazine", "/ˌmæɡəˈziːn/", "杂志"),
                w("visit", "/ˈvɪzɪt/", "参观"),
            ],
            "Unit 7 Summer holiday plans": [
                w("summer holiday", "/ˈsʌmə ˈhɒlɪdeɪ/", "暑假"),
                w("plan", "/plæn/", "计划"),
                w("go back to", "/ɡəʊ bæk tuː/", "回去"),
                w("parents", "/ˈpeərənts/", "父母"),
                w("Disneyland", "/ˈdɪznilænd/", "迪士尼乐园"),
                w("Ocean Park", "/ˈəʊʃən pɑːk/", "海洋公园"),
                w("Taipei", "/ˌtaɪˈpeɪ/", "台北"),
                w("travel", "/ˈtrævl/", "旅游"),
                w("around", "/əˈraʊnd/", "到处"),
                w("world", "/wɜːld/", "世界"),
                w("different", "/ˈdɪfrənt/", "不同的"),
            ],
            "Unit 8 Our dreams": [
                w("dream", "/driːm/", "梦想"),
                w("future", "/ˈfjuːtʃə/", "未来"),
                w("care about", "/keə əˈbaʊt/", "关心"),
                w("tooth", "/tuːθ/", "牙齿（复数 teeth）"),
                w("dentist", "/ˈdentɪst/", "牙医"),
                w("astronaut", "/ˈæstrənɔːt/", "宇航员"),
                w("spaceship", "/ˈspeɪsʃɪp/", "宇宙飞船"),
                w("football player", "/ˈfʊtbɔːl ˈpleɪə/", "足球运动员"),
                w("dancer", "/ˈdɑːnsə/", "舞蹈家"),
                w("pianist", "/piˈænɪst/", "钢琴家"),
                w("scientist", "/ˈsaɪəntɪst/", "科学家"),
                w("brave", "/breɪv/", "勇敢的"),
                w("artist", "/ˈɑːtɪst/", "艺术家"),
                w("come true", "/kʌm truː/", "实现"),
            ],
        }
    },
    "初一": {
        "上学期": {
            "Unit 1 This is me": [
                w("name", "/neɪm/", "名字"),
                w("age", "/eɪdʒ/", "年龄"),
                w("grade", "/ɡreɪd/", "年级"),
                w("class", "/klɑːs/", "班级"),
                w("school", "/skuːl/", "学校"),
                w("student", "/ˈstjuːdənt/", "学生"),
                w("from", "/frɒm/", "来自"),
                w("hobby", "/ˈhɒbi/", "爱好"),
                w("favourite", "/ˈfeɪvərɪt/", "最喜欢的"),
                w("subject", "/ˈsʌbdʒɪkt/", "科目"),
                w("tall", "/tɔːl/", "高的"),
                w("short", "/ʃɔːt/", "矮的"),
                w("thin", "/θɪn/", "瘦的"),
                w("friendly", "/ˈfrendli/", "友好的"),
                w("active", "/ˈæktɪv/", "积极的"),
            ],
            "Unit 2 Let's play sports": [
                w("sport", "/spɔːt/", "运动"),
                w("football", "/ˈfʊtbɔːl/", "足球"),
                w("basketball", "/ˈbɑːskɪtbɔːl/", "篮球"),
                w("tennis", "/ˈtenɪs/", "网球"),
                w("swimming", "/ˈswɪmɪŋ/", "游泳"),
                w("running", "/ˈrʌnɪŋ/", "跑步"),
                w("team", "/tiːm/", "队"),
                w("match", "/mætʃ/", "比赛"),
                w("win", "/wɪn/", "赢"),
                w("lose", "/luːz/", "输"),
                w("player", "/ˈpleɪə/", "运动员"),
                w("coach", "/kəʊtʃ/", "教练"),
                w("health", "/helθ/", "健康"),
                w("exercise", "/ˈeksəsaɪz/", "锻炼"),
                w("fit", "/fɪt/", "健康的"),
            ],
            "Unit 3 Welcome to our school": [
                w("classroom", "/ˈklɑːsruːm/", "教室"),
                w("library", "/ˈlaɪbrəri/", "图书馆"),
                w("office", "/ˈɒfɪs/", "办公室"),
                w("gym", "/dʒɪm/", "体育馆"),
                w("canteen", "/kænˈtiːn/", "食堂"),
                w("playground", "/ˈpleɪɡraʊnd/", "操场"),
                w("lab", "/læb/", "实验室"),
                w("building", "/ˈbɪldɪŋ/", "楼"),
                w("floor", "/flɔː/", "楼层"),
                w("toilet", "/ˈtɔɪlət/", "卫生间"),
                w("timetable", "/ˈtaɪmteɪbl/", "课程表"),
                w("lesson", "/ˈlesn/", "课"),
                w("period", "/ˈpɪəriəd/", "课时"),
                w("teacher", "/ˈtiːtʃə/", "教师"),
                w("welcome", "/ˈwelkəm/", "欢迎"),
            ],
            "Unit 4 My day": [
                w("get up", "/ɡet ʌp/", "起床"),
                w("breakfast", "/ˈbrekfəst/", "早餐"),
                w("lunch", "/lʌntʃ/", "午餐"),
                w("dinner", "/ˈdɪnə/", "晚餐"),
                w("homework", "/ˈhəʊmwɜːk/", "家庭作业"),
                w("o'clock", "/əˈklɒk/", "……点钟"),
                w("half", "/hɑːf/", "一半"),
                w("quarter", "/ˈkwɔːtə/", "一刻钟"),
                w("bus", "/bʌs/", "公共汽车"),
                w("walk", "/wɔːk/", "步行"),
                w("bike", "/baɪk/", "自行车"),
                w("usually", "/ˈjuːʒuəli/", "通常"),
                w("sometimes", "/ˈsʌmtaɪmz/", "有时"),
                w("always", "/ˈɔːlweɪz/", "总是"),
                w("never", "/ˈnevə/", "从不"),
            ],
            "Unit 5 Let's celebrate": [
                w("festival", "/ˈfestɪvl/", "节日"),
                w("holiday", "/ˈhɒlɪdeɪ/", "假日"),
                w("Spring Festival", "/sprɪŋ ˈfestɪvl/", "春节"),
                w("Christmas", "/ˈkrɪsməs/", "圣诞节"),
                w("birthday", "/ˈbɜːθdeɪ/", "生日"),
                w("party", "/ˈpɑːti/", "聚会"),
                w("gift", "/ɡɪft/", "礼物"),
                w("candle", "/ˈkændl/", "蜡烛"),
                w("cake", "/keɪk/", "蛋糕"),
                w("balloon", "/bəˈluːn/", "气球"),
                w("costume", "/ˈkɒstjuːm/", "服装"),
                w("decorate", "/ˈdekəreɪt/", "装饰"),
                w("celebrate", "/ˈselɪbreɪt/", "庆祝"),
                w("enjoy", "/ɪnˈdʒɔɪ/", "享受"),
                w("wish", "/wɪʃ/", "愿望"),
            ],
            "Unit 6 Food and lifestyle": [
                w("vegetable", "/ˈvedʒtəbl/", "蔬菜"),
                w("fruit", "/fruːt/", "水果"),
                w("rice", "/raɪs/", "米饭"),
                w("noodle", "/ˈnuːdl/", "面条"),
                w("meat", "/miːt/", "肉"),
                w("fish", "/fɪʃ/", "鱼"),
                w("healthy", "/ˈhelθi/", "健康的"),
                w("diet", "/ˈdaɪət/", "饮食"),
                w("meal", "/miːl/", "一餐"),
                w("drink", "/drɪŋk/", "饮料"),
                w("sugar", "/ˈʃʊɡə/", "糖"),
                w("salt", "/sɔːlt/", "盐"),
                w("taste", "/teɪst/", "味道"),
                w("delicious", "/dɪˈlɪʃəs/", "美味的"),
                w("enough", "/ɪˈnʌf/", "足够的"),
            ],
            "Unit 7 Shopping": [
                w("shop", "/ʃɒp/", "商店"),
                w("supermarket", "/ˈsuːpəmɑːkɪt/", "超市"),
                w("price", "/praɪs/", "价格"),
                w("cheap", "/tʃiːp/", "便宜的"),
                w("expensive", "/ɪkˈspensɪv/", "贵的"),
                w("pay", "/peɪ/", "付款"),
                w("change", "/tʃeɪndʒ/", "找零"),
                w("size", "/saɪz/", "尺码"),
                w("colour", "/ˈkʌlə/", "颜色"),
                w("try on", "/traɪ ɒn/", "试穿"),
                w("receipt", "/rɪˈsiːt/", "收据"),
                w("discount", "/ˈdɪskaʊnt/", "折扣"),
                w("cash", "/kæʃ/", "现金"),
                w("card", "/kɑːd/", "卡"),
                w("customer", "/ˈkʌstəmə/", "顾客"),
            ],
            "Unit 8 Fashion": [
                w("clothes", "/kləʊðz/", "衣服"),
                w("shirt", "/ʃɜːt/", "衬衫"),
                w("trousers", "/ˈtraʊzəz/", "裤子"),
                w("skirt", "/skɜːt/", "裙子"),
                w("dress", "/dres/", "连衣裙"),
                w("jacket", "/ˈdʒækɪt/", "夹克"),
                w("coat", "/kəʊt/", "外套"),
                w("shoes", "/ʃuːz/", "鞋"),
                w("hat", "/hæt/", "帽子"),
                w("scarf", "/skɑːf/", "围巾"),
                w("fashion", "/ˈfæʃn/", "时尚"),
                w("style", "/staɪl/", "风格"),
                w("wear", "/weə/", "穿"),
                w("match", "/mætʃ/", "搭配"),
                w("popular", "/ˈpɒpjʊlə/", "流行的"),
            ],
        },
        "下学期": {
            "Unit 1 Dream homes": [
                w("home", "/həʊm/", "家"),
                w("house", "/haʊs/", "房子"),
                w("flat", "/flæt/", "公寓"),
                w("room", "/ruːm/", "房间"),
                w("bedroom", "/ˈbedruːm/", "卧室"),
                w("kitchen", "/ˈkɪtʃɪn/", "厨房"),
                w("bathroom", "/ˈbɑːθruːm/", "浴室"),
                w("living room", "/ˈlɪvɪŋ ruːm/", "客厅"),
                w("garden", "/ˈɡɑːdn/", "花园"),
                w("furniture", "/ˈfɜːnɪtʃə/", "家具"),
                w("sofa", "/ˈsəʊfə/", "沙发"),
                w("curtain", "/ˈkɜːtn/", "窗帘"),
                w("wall", "/wɔːl/", "墙"),
                w("ceiling", "/ˈsiːlɪŋ/", "天花板"),
                w("dream", "/driːm/", "梦想"),
            ],
            "Unit 2 Neighbours": [
                w("neighbour", "/ˈneɪbə/", "邻居"),
                w("community", "/kəˈmjuːnɪti/", "社区"),
                w("helpful", "/ˈhelpfl/", "乐于助人的"),
                w("friendly", "/ˈfrendli/", "友好的"),
                w("polite", "/pəˈlaɪt/", "有礼貌的"),
                w("loud", "/laʊd/", "吵闹的"),
                w("quiet", "/ˈkwaɪət/", "安静的"),
                w("noisy", "/ˈnɔɪzi/", "嘈杂的"),
                w("borrow", "/ˈbɒrəʊ/", "借（入）"),
                w("lend", "/lend/", "借（出）"),
                w("knock", "/nɒk/", "敲"),
                w("invite", "/ɪnˈvaɪt/", "邀请"),
                w("welcome", "/ˈwelkəm/", "欢迎"),
                w("introduce", "/ˌɪntrəˈdjuːs/", "介绍"),
                w("trust", "/trʌst/", "信任"),
            ],
            "Unit 3 Finding your way": [
                w("turn left", "/tɜːn left/", "向左转"),
                w("turn right", "/tɜːn raɪt/", "向右转"),
                w("go straight", "/ɡəʊ streɪt/", "直走"),
                w("crossroads", "/ˈkrɒsrəʊdz/", "十字路口"),
                w("traffic light", "/ˈtræfɪk laɪt/", "交通灯"),
                w("bridge", "/brɪdʒ/", "桥"),
                w("station", "/ˈsteɪʃn/", "车站"),
                w("hospital", "/ˈhɒspɪtl/", "医院"),
                w("park", "/pɑːk/", "公园"),
                w("museum", "/mjuːˈziːəm/", "博物馆"),
                w("map", "/mæp/", "地图"),
                w("direction", "/dɪˈrekʃn/", "方向"),
                w("north", "/nɔːθ/", "北"),
                w("south", "/saʊθ/", "南"),
                w("kilometre", "/ˈkɪləmiːtə/", "千米"),
            ],
            "Unit 4 A taste of English poetry": [
                w("poem", "/ˈpəʊɪm/", "诗"),
                w("poet", "/ˈpəʊɪt/", "诗人"),
                w("nature", "/ˈneɪtʃə/", "自然"),
                w("beauty", "/ˈbjuːti/", "美"),
                w("season", "/ˈsiːzn/", "季节"),
                w("spring", "/sprɪŋ/", "春天"),
                w("summer", "/ˈsʌmə/", "夏天"),
                w("autumn", "/ˈɔːtəm/", "秋天"),
                w("winter", "/ˈwɪntə/", "冬天"),
                w("leaf", "/liːf/", "叶子"),
                w("flower", "/ˈflaʊə/", "花"),
                w("river", "/ˈrɪvə/", "河"),
                w("mountain", "/ˈmaʊntɪn/", "山"),
                w("sky", "/skaɪ/", "天空"),
                w("rhyme", "/raɪm/", "押韵"),
            ],
            "Unit 5 Going shopping": [
                w("mall", "/mɔːl/", "购物中心"),
                w("department store", "/dɪˈpɑːtmənt stɔː/", "百货商店"),
                w("brand", "/brænd/", "品牌"),
                w("quality", "/ˈkwɒlɪti/", "质量"),
                w("refund", "/ˈriːfʌnd/", "退款"),
                w("exchange", "/ɪksˈtʃeɪndʒ/", "换货"),
                w("queue", "/kjuː/", "排队"),
                w("counter", "/ˈkaʊntə/", "柜台"),
                w("fitting room", "/ˈfɪtɪŋ ruːm/", "试衣间"),
                w("bill", "/bɪl/", "账单"),
                w("receipt", "/rɪˈsiːt/", "收据"),
                w("online", "/ˈɒnlaɪn/", "网上"),
                w("deliver", "/dɪˈlɪvə/", "递送"),
                w("offer", "/ˈɒfə/", "提供"),
                w("choice", "/tʃɔɪs/", "选择"),
            ],
            "Unit 6 Outdoor fun": [
                w("outdoor", "/ˈaʊtdɔː/", "户外的"),
                w("camping", "/ˈkæmpɪŋ/", "露营"),
                w("hiking", "/ˈhaɪkɪŋ/", "徒步旅行"),
                w("climbing", "/ˈklaɪmɪŋ/", "攀登"),
                w("picnic", "/ˈpɪknɪk/", "野餐"),
                w("tent", "/tent/", "帐篷"),
                w("backpack", "/ˈbækpæk/", "背包"),
                w("compass", "/ˈkʌmpəs/", "指南针"),
                w("torch", "/tɔːtʃ/", "手电筒"),
                w("insect", "/ˈɪnsekt/", "昆虫"),
                w("sunscreen", "/ˈsʌnskriːn/", "防晒霜"),
                w("adventure", "/ədˈventʃə/", "冒险"),
                w("explore", "/ɪkˈsplɔː/", "探索"),
                w("nature", "/ˈneɪtʃə/", "自然"),
                w("fresh air", "/freʃ eə/", "新鲜空气"),
            ],
            "Unit 7 Problems": [
                w("problem", "/ˈprɒbləm/", "问题"),
                w("trouble", "/ˈtrʌbl/", "麻烦"),
                w("worry", "/ˈwʌri/", "担心"),
                w("stress", "/stres/", "压力"),
                w("advice", "/ədˈvaɪs/", "建议"),
                w("solution", "/səˈluːʃn/", "解决方案"),
                w("discuss", "/dɪˈskʌs/", "讨论"),
                w("share", "/ʃeə/", "分享"),
                w("disagree", "/ˌdɪsəˈɡriː/", "不同意"),
                w("argue", "/ˈɑːɡjuː/", "争论"),
                w("forgive", "/fəˈɡɪv/", "原谅"),
                w("apologize", "/əˈpɒlədʒaɪz/", "道歉"),
                w("solve", "/sɒlv/", "解决"),
                w("calm", "/kɑːm/", "冷静的"),
                w("patient", "/ˈpeɪʃnt/", "有耐心的"),
            ],
            "Unit 8 Pets": [
                w("pet", "/pet/", "宠物"),
                w("dog", "/dɒɡ/", "狗"),
                w("cat", "/kæt/", "猫"),
                w("rabbit", "/ˈræbɪt/", "兔子"),
                w("hamster", "/ˈhæmstə/", "仓鼠"),
                w("parrot", "/ˈpærət/", "鹦鹉"),
                w("feed", "/fiːd/", "喂食"),
                w("walk", "/wɔːk/", "遛（狗）"),
                w("groom", "/ɡruːm/", "梳洗"),
                w("vet", "/vet/", "兽医"),
                w("fur", "/fɜː/", "皮毛"),
                w("tail", "/teɪl/", "尾巴"),
                w("paw", "/pɔː/", "爪子"),
                w("bark", "/bɑːk/", "吠叫"),
                w("loyal", "/ˈlɔɪəl/", "忠诚的"),
            ],
        },
    },
    "初二": {
        "上学期": {
            "Unit 1 Friends": [
                w("friendship", "/ˈfrendʃɪp/", "友谊"),
                w("honest", "/ˈɒnɪst/", "诚实的"),
                w("humorous", "/ˈhjuːmərəs/", "幽默的"),
                w("generous", "/ˈdʒenərəs/", "大方的"),
                w("brave", "/breɪv/", "勇敢的"),
                w("clever", "/ˈklevə/", "聪明的"),
                w("share", "/ʃeə/", "分享"),
                w("trust", "/trʌst/", "信任"),
                w("support", "/səˈpɔːt/", "支持"),
                w("loyal", "/ˈlɔɪəl/", "忠诚的"),
                w("agree", "/əˈɡriː/", "同意"),
                w("respect", "/rɪˈspekt/", "尊重"),
                w("misunderstand", "/ˌmɪsʌndəˈstænd/", "误解"),
                w("argue", "/ˈɑːɡjuː/", "争论"),
                w("make up", "/meɪk ʌp/", "和好"),
            ],
            "Unit 2 School life": [
                w("uniform", "/ˈjuːnɪfɔːm/", "校服"),
                w("rules", "/ruːlz/", "规则"),
                w("club", "/klʌb/", "俱乐部"),
                w("activity", "/ækˈtɪvɪti/", "活动"),
                w("volunteer", "/ˌvɒlənˈtɪə/", "志愿者"),
                w("assembly", "/əˈsembli/", "集会"),
                w("exam", "/ɪɡˈzæm/", "考试"),
                w("grade", "/ɡreɪd/", "成绩"),
                w("scholarship", "/ˈskɒləʃɪp/", "奖学金"),
                w("study", "/ˈstʌdi/", "学习"),
                w("strict", "/strɪkt/", "严格的"),
                w("absent", "/ˈæbsənt/", "缺席的"),
                w("punish", "/ˈpʌnɪʃ/", "惩罚"),
                w("reward", "/rɪˈwɔːd/", "奖励"),
                w("progress", "/ˈprəʊɡres/", "进步"),
            ],
            "Unit 3 A day out": [
                w("trip", "/trɪp/", "旅行"),
                w("tour", "/tʊə/", "游览"),
                w("visit", "/ˈvɪzɪt/", "参观"),
                w("ticket", "/ˈtɪkɪt/", "票"),
                w("entrance", "/ˈentrəns/", "入口"),
                w("scenery", "/ˈsiːnəri/", "风景"),
                w("souvenir", "/ˌsuːvəˈnɪə/", "纪念品"),
                w("photograph", "/ˈfəʊtəɡrɑːf/", "照片"),
                w("guide", "/ɡaɪd/", "导游"),
                w("queue", "/kjuː/", "排队"),
                w("crowd", "/kraʊd/", "人群"),
                w("amazing", "/əˈmeɪzɪŋ/", "令人惊叹的"),
                w("wonderful", "/ˈwʌndəfl/", "精彩的"),
                w("experience", "/ɪkˈspɪəriəns/", "经历"),
                w("memory", "/ˈmeməri/", "记忆"),
            ],
            "Unit 4 A good read": [
                w("novel", "/ˈnɒvl/", "小说"),
                w("author", "/ˈɔːθə/", "作者"),
                w("character", "/ˈkærəktə/", "人物"),
                w("plot", "/plɒt/", "情节"),
                w("chapter", "/ˈtʃæptə/", "章节"),
                w("fiction", "/ˈfɪkʃn/", "小说"),
                w("adventure", "/ədˈventʃə/", "冒险"),
                w("mystery", "/ˈmɪstəri/", "谜"),
                w("hero", "/ˈhɪərəʊ/", "英雄"),
                w("villain", "/ˈvɪlən/", "反派"),
                w("setting", "/ˈsetɪŋ/", "背景"),
                w("ending", "/ˈendɪŋ/", "结局"),
                w("recommend", "/ˌrekəˈmend/", "推荐"),
                w("review", "/rɪˈvjuː/", "评论"),
                w("imagine", "/ɪˈmædʒɪn/", "想象"),
            ],
            "Unit 5 Wild animals": [
                w("wildlife", "/ˈwaɪldlaɪf/", "野生动物"),
                w("tiger", "/ˈtaɪɡə/", "老虎"),
                w("elephant", "/ˈelɪfənt/", "大象"),
                w("giant panda", "/ˈdʒaɪənt ˈpændə/", "大熊猫"),
                w("dolphin", "/ˈdɒlfɪn/", "海豚"),
                w("endangered", "/ɪnˈdeɪndʒəd/", "濒危的"),
                w("extinct", "/ɪkˈstɪŋkt/", "灭绝的"),
                w("protect", "/prəˈtekt/", "保护"),
                w("habitat", "/ˈhæbɪtæt/", "栖息地"),
                w("hunt", "/hʌnt/", "猎杀"),
                w("survive", "/səˈvaɪv/", "生存"),
                w("species", "/ˈspiːʃiːz/", "物种"),
                w("nature reserve", "/ˈneɪtʃə rɪˈzɜːv/", "自然保护区"),
                w("wild", "/waɪld/", "野生的"),
                w("conservation", "/ˌkɒnsəˈveɪʃn/", "保护"),
            ],
            "Unit 6 Natural disasters": [
                w("earthquake", "/ˈɜːθkweɪk/", "地震"),
                w("flood", "/flʌd/", "洪水"),
                w("typhoon", "/taɪˈfuːn/", "台风"),
                w("hurricane", "/ˈhʌrɪkən/", "飓风"),
                w("volcano", "/vɒlˈkeɪnəʊ/", "火山"),
                w("tsunami", "/tsuːˈnɑːmi/", "海啸"),
                w("drought", "/draʊt/", "干旱"),
                w("damage", "/ˈdæmɪdʒ/", "破坏"),
                w("rescue", "/ˈreskjuː/", "救援"),
                w("survivor", "/səˈvaɪvə/", "幸存者"),
                w("shelter", "/ˈʃeltə/", "避难所"),
                w("disaster", "/dɪˈzɑːstə/", "灾难"),
                w("relief", "/rɪˈliːf/", "救援"),
                w("evacuate", "/ɪˈvækjueɪt/", "疏散"),
                w("danger", "/ˈdeɪndʒə/", "危险"),
            ],
            "Unit 7 Seasons": [
                w("temperature", "/ˈtemprətʃə/", "温度"),
                w("degree", "/dɪˈɡriː/", "度"),
                w("weather forecast", "/ˈweðə ˈfɔːkɑːst/", "天气预报"),
                w("cloudy", "/ˈklaʊdi/", "多云的"),
                w("sunny", "/ˈsʌni/", "晴朗的"),
                w("rainy", "/ˈreɪni/", "下雨的"),
                w("windy", "/ˈwɪndi/", "刮风的"),
                w("snowy", "/ˈsnəʊi/", "下雪的"),
                w("foggy", "/ˈfɒɡi/", "有雾的"),
                w("thunder", "/ˈθʌndə/", "雷声"),
                w("lightning", "/ˈlaɪtnɪŋ/", "闪电"),
                w("rainbow", "/ˈreɪnbəʊ/", "彩虹"),
                w("humid", "/ˈhjuːmɪd/", "潮湿的"),
                w("freezing", "/ˈfriːzɪŋ/", "冰冻的"),
                w("boiling", "/ˈbɔɪlɪŋ/", "滚烫的"),
            ],
            "Unit 8 Fashion and shopping": [
                w("trend", "/trend/", "趋势"),
                w("design", "/dɪˈzaɪn/", "设计"),
                w("designer", "/dɪˈzaɪnə/", "设计师"),
                w("brand", "/brænd/", "品牌"),
                w("material", "/məˈtɪəriəl/", "材料"),
                w("cotton", "/ˈkɒtn/", "棉"),
                w("silk", "/sɪlk/", "丝绸"),
                w("leather", "/ˈleðə/", "皮革"),
                w("loose", "/luːs/", "宽松的"),
                w("tight", "/taɪt/", "紧身的"),
                w("stripe", "/straɪp/", "条纹"),
                w("pattern", "/ˈpætn/", "图案"),
                w("formal", "/ˈfɔːml/", "正式的"),
                w("casual", "/ˈkæʒuəl/", "休闲的"),
                w("accessory", "/əkˈsesəri/", "配件"),
            ],
        },
        "下学期": {
            "Unit 1 Past and present": [
                w("past", "/pɑːst/", "过去"),
                w("present", "/ˈpreznt/", "现在"),
                w("history", "/ˈhɪstri/", "历史"),
                w("ancient", "/ˈeɪnʃənt/", "古代的"),
                w("modern", "/ˈmɒdn/", "现代的"),
                w("change", "/tʃeɪndʒ/", "改变"),
                w("develop", "/dɪˈveləp/", "发展"),
                w("technology", "/tekˈnɒlədʒi/", "技术"),
                w("invention", "/ɪnˈvenʃn/", "发明"),
                w("traditional", "/trəˈdɪʃənl/", "传统的"),
                w("custom", "/ˈkʌstəm/", "习俗"),
                w("culture", "/ˈkʌltʃə/", "文化"),
                w("generation", "/ˌdʒenəˈreɪʃn/", "代"),
                w("compare", "/kəmˈpeə/", "比较"),
                w("progress", "/ˈprəʊɡres/", "进步"),
            ],
            "Unit 2 Travelling": [
                w("journey", "/ˈdʒɜːni/", "旅程"),
                w("destination", "/ˌdestɪˈneɪʃn/", "目的地"),
                w("passport", "/ˈpɑːspɔːt/", "护照"),
                w("visa", "/ˈviːzə/", "签证"),
                w("luggage", "/ˈlʌɡɪdʒ/", "行李"),
                w("airport", "/ˈeəpɔːt/", "机场"),
                w("flight", "/flaɪt/", "航班"),
                w("hotel", "/həʊˈtel/", "酒店"),
                w("check in", "/tʃek ɪn/", "办理入住"),
                w("customs", "/ˈkʌstəmz/", "海关"),
                w("exchange rate", "/ɪksˈtʃeɪndʒ reɪt/", "汇率"),
                w("local", "/ˈləʊkl/", "当地的"),
                w("culture shock", "/ˈkʌltʃə ʃɒk/", "文化冲击"),
                w("recommend", "/ˌrekəˈmend/", "推荐"),
                w("accommodation", "/əˌkɒməˈdeɪʃn/", "住宿"),
            ],
            "Unit 3 Online travel": [
                w("website", "/ˈwebsaɪt/", "网站"),
                w("internet", "/ˈɪntənet/", "互联网"),
                w("search", "/sɜːtʃ/", "搜索"),
                w("download", "/ˈdaʊnləʊd/", "下载"),
                w("upload", "/ˈʌpləʊd/", "上传"),
                w("social media", "/ˈsəʊʃl ˈmiːdiə/", "社交媒体"),
                w("post", "/pəʊst/", "发布"),
                w("comment", "/ˈkɒment/", "评论"),
                w("share", "/ʃeə/", "分享"),
                w("follower", "/ˈfɒləʊə/", "粉丝"),
                w("blog", "/blɒɡ/", "博客"),
                w("video", "/ˈvɪdiəʊ/", "视频"),
                w("stream", "/striːm/", "直播"),
                w("virtual", "/ˈvɜːtʃuəl/", "虚拟的"),
                w("digital", "/ˈdɪdʒɪtl/", "数字的"),
            ],
            "Unit 4 A charity show": [
                w("charity", "/ˈtʃærɪti/", "慈善"),
                w("donate", "/dəˈneɪt/", "捐赠"),
                w("donation", "/dəˈneɪʃn/", "捐款"),
                w("raise", "/reɪz/", "筹集"),
                w("fund", "/fʌnd/", "基金"),
                w("performance", "/pəˈfɔːməns/", "表演"),
                w("stage", "/steɪdʒ/", "舞台"),
                w("audience", "/ˈɔːdiəns/", "观众"),
                w("rehearsal", "/rɪˈhɜːsl/", "排练"),
                w("costume", "/ˈkɒstjuːm/", "服装"),
                w("volunteer", "/ˌvɒlənˈtɪə/", "志愿者"),
                w("organize", "/ˈɔːɡənaɪz/", "组织"),
                w("event", "/ɪˈvent/", "活动"),
                w("support", "/səˈpɔːt/", "支持"),
                w("generous", "/ˈdʒenərəs/", "慷慨的"),
            ],
            "Unit 5 Good manners": [
                w("manner", "/ˈmænə/", "礼貌"),
                w("polite", "/pəˈlaɪt/", "有礼貌的"),
                w("rude", "/ruːd/", "粗鲁的"),
                w("etiquette", "/ˈetɪket/", "礼仪"),
                w("greet", "/ɡriːt/", "问候"),
                w("apologize", "/əˈpɒlədʒaɪz/", "道歉"),
                w("behave", "/bɪˈheɪv/", "表现"),
                w("respect", "/rɪˈspekt/", "尊重"),
                w("queue", "/kjuː/", "排队"),
                w("interrupt", "/ˌɪntəˈrʌpt/", "打断"),
                w("whisper", "/ˈwɪspə/", "低声说"),
                w("gesture", "/ˈdʒestʃə/", "手势"),
                w("custom", "/ˈkʌstəm/", "习俗"),
                w("culture", "/ˈkʌltʃə/", "文化"),
                w("appropriate", "/əˈprəʊpriət/", "适当的"),
            ],
            "Unit 6 An old man's story": [
                w("elderly", "/ˈeldəli/", "年老的"),
                w("experience", "/ɪkˈspɪəriəns/", "经历"),
                w("memory", "/ˈmeməri/", "记忆"),
                w("career", "/kəˈrɪə/", "职业"),
                w("retire", "/rɪˈtaɪə/", "退休"),
                w("achieve", "/əˈtʃiːv/", "实现"),
                w("success", "/səkˈses/", "成功"),
                w("struggle", "/ˈstrʌɡl/", "奋斗"),
                w("persevere", "/ˌpɜːsɪˈvɪə/", "坚持"),
                w("inspire", "/ɪnˈspaɪə/", "激励"),
                w("wisdom", "/ˈwɪzdəm/", "智慧"),
                w("regret", "/rɪˈɡret/", "遗憾"),
                w("proud", "/praʊd/", "自豪的"),
                w("grateful", "/ˈɡreɪtfl/", "感激的"),
                w("lesson", "/ˈlesn/", "教训"),
            ],
            "Unit 7 International charities": [
                w("international", "/ˌɪntəˈnæʃənl/", "国际的"),
                w("organization", "/ˌɔːɡənaɪˈzeɪʃn/", "组织"),
                w("poverty", "/ˈpɒvəti/", "贫困"),
                w("hunger", "/ˈhʌŋɡə/", "饥饿"),
                w("education", "/ˌedʒuˈkeɪʃn/", "教育"),
                w("environment", "/ɪnˈvaɪrənmənt/", "环境"),
                w("campaign", "/kæmˈpeɪn/", "运动"),
                w("awareness", "/əˈweənəs/", "意识"),
                w("global", "/ˈɡləʊbl/", "全球的"),
                w("community", "/kəˈmjuːnɪti/", "社区"),
                w("impact", "/ˈɪmpækt/", "影响"),
                w("solution", "/səˈluːʃn/", "解决方案"),
                w("resources", "/rɪˈzɔːsɪz/", "资源"),
                w("equality", "/ɪˈkwɒlɪti/", "平等"),
                w("justice", "/ˈdʒʌstɪs/", "公正"),
            ],
            "Unit 8 A green world": [
                w("environment", "/ɪnˈvaɪrənmənt/", "环境"),
                w("pollution", "/pəˈluːʃn/", "污染"),
                w("recycle", "/ˌriːˈsaɪkl/", "回收"),
                w("renewable", "/rɪˈnjuːəbl/", "可再生的"),
                w("energy", "/ˈenədʒi/", "能源"),
                w("solar", "/ˈsəʊlə/", "太阳能的"),
                w("carbon", "/ˈkɑːbən/", "碳"),
                w("greenhouse", "/ˈɡriːnhaʊs/", "温室"),
                w("global warming", "/ˈɡləʊbl ˈwɔːmɪŋ/", "全球变暖"),
                w("deforestation", "/ˌdiːˌfɒrɪˈsteɪʃn/", "滥伐森林"),
                w("species", "/ˈspiːʃiːz/", "物种"),
                w("sustainable", "/səˈsteɪnəbl/", "可持续的"),
                w("reduce", "/rɪˈdjuːs/", "减少"),
                w("reuse", "/ˌriːˈjuːz/", "再使用"),
                w("protect", "/prəˈtekt/", "保护"),
            ],
        },
    },
    "初三": {
        "上学期": {
            "Unit 1 Star signs": [
                w("star sign", "/stɑː saɪn/", "星座"),
                w("horoscope", "/ˈhɒrəskəʊp/", "星相"),
                w("personality", "/ˌpɜːsəˈnælɪti/", "性格"),
                w("character", "/ˈkærəktə/", "性格特点"),
                w("ambitious", "/æmˈbɪʃəs/", "有野心的"),
                w("sensitive", "/ˈsensɪtɪv/", "敏感的"),
                w("confident", "/ˈkɒnfɪdənt/", "自信的"),
                w("creative", "/kriˈeɪtɪv/", "有创造力的"),
                w("stubborn", "/ˈstʌbən/", "固执的"),
                w("patient", "/ˈpeɪʃnt/", "有耐心的"),
                w("optimistic", "/ˌɒptɪˈmɪstɪk/", "乐观的"),
                w("pessimistic", "/ˌpesɪˈmɪstɪk/", "悲观的"),
                w("loyal", "/ˈlɔɪəl/", "忠诚的"),
                w("independent", "/ˌɪndɪˈpendənt/", "独立的"),
                w("curious", "/ˈkjʊəriəs/", "好奇的"),
            ],
            "Unit 2 Colour and light": [
                w("colour", "/ˈkʌlə/", "颜色"),
                w("light", "/laɪt/", "光"),
                w("spectrum", "/ˈspektrəm/", "光谱"),
                w("wavelength", "/ˈweɪvleŋθ/", "波长"),
                w("primary colour", "/ˈpraɪməri ˈkʌlə/", "原色"),
                w("reflect", "/rɪˈflekt/", "反射"),
                w("absorb", "/əbˈzɔːb/", "吸收"),
                w("mixture", "/ˈmɪkstʃə/", "混合"),
                w("symbol", "/ˈsɪmbl/", "象征"),
                w("mood", "/muːd/", "心情"),
                w("emotion", "/ɪˈməʊʃn/", "情感"),
                w("influence", "/ˈɪnfluəns/", "影响"),
                w("psychology", "/saɪˈkɒlədʒi/", "心理学"),
                w("contrast", "/ˈkɒntrɑːst/", "对比"),
                w("vivid", "/ˈvɪvɪd/", "鲜艳的"),
            ],
            "Unit 3 Teenage problems": [
                w("teenager", "/ˈtiːneɪdʒə/", "青少年"),
                w("pressure", "/ˈpreʃə/", "压力"),
                w("anxiety", "/æŋˈzaɪəti/", "焦虑"),
                w("depression", "/dɪˈpreʃn/", "抑郁"),
                w("peer pressure", "/pɪə ˈpreʃə/", "同伴压力"),
                w("bully", "/ˈbʊli/", "霸凌"),
                w("self-esteem", "/ˌself ɪˈstiːm/", "自尊"),
                w("communicate", "/kəˈmjuːnɪkeɪt/", "沟通"),
                w("counsellor", "/ˈkaʊnsələ/", "心理咨询师"),
                w("mental health", "/ˈmentl helθ/", "心理健康"),
                w("cope with", "/kəʊp wɪð/", "应对"),
                w("overcome", "/ˌəʊvəˈkʌm/", "克服"),
                w("confidence", "/ˈkɒnfɪdəns/", "信心"),
                w("support", "/səˈpɔːt/", "支持"),
                w("positive", "/ˈpɒzɪtɪv/", "积极的"),
            ],
            "Unit 4 Growing up": [
                w("growth", "/ɡrəʊθ/", "成长"),
                w("mature", "/məˈtʃʊə/", "成熟的"),
                w("responsibility", "/rɪˌspɒnsɪˈbɪlɪti/", "责任"),
                w("independent", "/ˌɪndɪˈpendənt/", "独立的"),
                w("decision", "/dɪˈsɪʒn/", "决定"),
                w("challenge", "/ˈtʃælɪndʒ/", "挑战"),
                w("experience", "/ɪkˈspɪəriəns/", "经历"),
                w("talent", "/ˈtælənt/", "才能"),
                w("ambition", "/æmˈbɪʃn/", "雄心"),
                w("goal", "/ɡəʊl/", "目标"),
                w("achievement", "/əˈtʃiːvmənt/", "成就"),
                w("failure", "/ˈfeɪljə/", "失败"),
                w("lesson", "/ˈlesn/", "教训"),
                w("opportunity", "/ˌɒpəˈtjuːnɪti/", "机会"),
                w("potential", "/pəˈtenʃl/", "潜力"),
            ],
            "Unit 5 Films and stories": [
                w("film", "/fɪlm/", "电影"),
                w("director", "/dɪˈrektə/", "导演"),
                w("actor", "/ˈæktə/", "演员"),
                w("actress", "/ˈæktrəs/", "女演员"),
                w("script", "/skrɪpt/", "剧本"),
                w("scene", "/siːn/", "场景"),
                w("special effects", "/ˈspeʃl ɪˈfekts/", "特效"),
                w("animation", "/ˌænɪˈmeɪʃn/", "动画"),
                w("documentary", "/ˌdɒkjuˈmentri/", "纪录片"),
                w("comedy", "/ˈkɒmədi/", "喜剧"),
                w("thriller", "/ˈθrɪlə/", "惊悚片"),
                w("romance", "/rəˈmæns/", "爱情片"),
                w("award", "/əˈwɔːd/", "奖项"),
                w("review", "/rɪˈvjuː/", "评论"),
                w("audience", "/ˈɔːdiəns/", "观众"),
            ],
            "Unit 6 TV programmes": [
                w("programme", "/ˈprəʊɡræm/", "节目"),
                w("channel", "/ˈtʃænl/", "频道"),
                w("broadcast", "/ˈbrɔːdkɑːst/", "播放"),
                w("presenter", "/prɪˈzentə/", "主持人"),
                w("interview", "/ˈɪntəvjuː/", "采访"),
                w("news", "/njuːz/", "新闻"),
                w("documentary", "/ˌdɒkjuˈmentri/", "纪录片"),
                w("reality show", "/riˈælɪti ʃəʊ/", "真人秀"),
                w("cartoon", "/kɑːˈtuːn/", "卡通"),
                w("advertisement", "/ədˈvɜːtɪsmənt/", "广告"),
                w("ratings", "/ˈreɪtɪŋz/", "收视率"),
                w("subtitle", "/ˈsʌbtaɪtl/", "字幕"),
                w("episode", "/ˈepɪsəʊd/", "集"),
                w("series", "/ˈsɪəriːz/", "系列"),
                w("influence", "/ˈɪnfluəns/", "影响"),
            ],
            "Unit 7 Film-making": [
                w("camera", "/ˈkæmərə/", "摄影机"),
                w("crew", "/kruː/", "剧组"),
                w("producer", "/prəˈdjuːsə/", "制片人"),
                w("location", "/ləʊˈkeɪʃn/", "拍摄地点"),
                w("studio", "/ˈstjuːdiəʊ/", "摄影棚"),
                w("costume", "/ˈkɒstjuːm/", "服装"),
                w("make-up", "/ˈmeɪk ʌp/", "化妆"),
                w("soundtrack", "/ˈsaʊndtræk/", "原声带"),
                w("editing", "/ˈedɪtɪŋ/", "剪辑"),
                w("budget", "/ˈbʌdʒɪt/", "预算"),
                w("release", "/rɪˈliːs/", "发行"),
                w("box office", "/bɒks ˈɒfɪs/", "票房"),
                w("premiere", "/ˈpremieə/", "首映"),
                w("sequel", "/ˈsiːkwəl/", "续集"),
                w("remake", "/ˌriːˈmeɪk/", "翻拍"),
            ],
            "Unit 8 Chinese history and culture": [
                w("civilization", "/ˌsɪvɪlaɪˈzeɪʃn/", "文明"),
                w("dynasty", "/ˈdɪnəsti/", "朝代"),
                w("emperor", "/ˈempərə/", "皇帝"),
                w("ancient", "/ˈeɪnʃənt/", "古代的"),
                w("heritage", "/ˈherɪtɪdʒ/", "遗产"),
                w("tradition", "/trəˈdɪʃn/", "传统"),
                w("philosophy", "/fɪˈlɒsəfi/", "哲学"),
                w("invention", "/ɪnˈvenʃn/", "发明"),
                w("silk road", "/sɪlk rəʊd/", "丝绸之路"),
                w("Great Wall", "/ɡreɪt wɔːl/", "长城"),
                w("calligraphy", "/kəˈlɪɡrəfi/", "书法"),
                w("martial arts", "/ˈmɑːʃl ɑːts/", "武术"),
                w("porcelain", "/ˈpɔːsəlɪn/", "瓷器"),
                w("influence", "/ˈɪnfluəns/", "影响"),
                w("pride", "/praɪd/", "自豪"),
            ],
        },
        "下学期": {
            "Unit 1 Life on Mars": [
                w("Mars", "/mɑːz/", "火星"),
                w("planet", "/ˈplænɪt/", "行星"),
                w("space", "/speɪs/", "太空"),
                w("astronaut", "/ˈæstrənɔːt/", "宇航员"),
                w("spacecraft", "/ˈspeɪskrɑːft/", "宇宙飞船"),
                w("gravity", "/ˈɡrævɪti/", "重力"),
                w("atmosphere", "/ˈætməsfɪə/", "大气层"),
                w("oxygen", "/ˈɒksɪdʒən/", "氧气"),
                w("explore", "/ɪkˈsplɔː/", "探索"),
                w("colony", "/ˈkɒləni/", "殖民地"),
                w("telescope", "/ˈtelɪskəʊp/", "望远镜"),
                w("galaxy", "/ˈɡæləksi/", "星系"),
                w("universe", "/ˈjuːnɪvɜːs/", "宇宙"),
                w("satellite", "/ˈsætəlaɪt/", "卫星"),
                w("mission", "/ˈmɪʃn/", "任务"),
            ],
            "Unit 2 Robots": [
                w("robot", "/ˈrəʊbɒt/", "机器人"),
                w("artificial intelligence", "/ˌɑːtɪˈfɪʃl ɪnˈtelɪdʒəns/", "人工智能"),
                w("technology", "/tekˈnɒlədʒi/", "技术"),
                w("programme", "/ˈprəʊɡræm/", "编程"),
                w("computer", "/kəmˈpjuːtə/", "计算机"),
                w("machine", "/məˈʃiːn/", "机器"),
                w("automatic", "/ˌɔːtəˈmætɪk/", "自动的"),
                w("human", "/ˈhjuːmən/", "人类的"),
                w("replace", "/rɪˈpleɪs/", "取代"),
                w("intelligent", "/ɪnˈtelɪdʒənt/", "智能的"),
                w("invention", "/ɪnˈvenʃn/", "发明"),
                w("factory", "/ˈfæktri/", "工厂"),
                w("labour", "/ˈleɪbə/", "劳动"),
                w("future", "/ˈfjuːtʃə/", "未来"),
                w("digital", "/ˈdɪdʒɪtl/", "数字的"),
            ],
            "Unit 3 Asia": [
                w("Asia", "/ˈeɪʒə/", "亚洲"),
                w("continent", "/ˈkɒntɪnənt/", "洲"),
                w("country", "/ˈkʌntri/", "国家"),
                w("capital", "/ˈkæpɪtl/", "首都"),
                w("population", "/ˌpɒpjuˈleɪʃn/", "人口"),
                w("currency", "/ˈkʌrənsi/", "货币"),
                w("language", "/ˈlæŋɡwɪdʒ/", "语言"),
                w("religion", "/rɪˈlɪdʒən/", "宗教"),
                w("culture", "/ˈkʌltʃə/", "文化"),
                w("geography", "/dʒiˈɒɡrəfi/", "地理"),
                w("climate", "/ˈklaɪmɪt/", "气候"),
                w("landmark", "/ˈlændmɑːk/", "地标"),
                w("tourist", "/ˈtʊərɪst/", "游客"),
                w("economy", "/ɪˈkɒnəmi/", "经济"),
                w("developing", "/dɪˈveləpɪŋ/", "发展中的"),
            ],
            "Unit 4 Australia": [
                w("Australia", "/ɒˈstreɪliə/", "澳大利亚"),
                w("Sydney", "/ˈsɪdni/", "悉尼"),
                w("kangaroo", "/ˌkæŋɡəˈruː/", "袋鼠"),
                w("koala", "/kəʊˈɑːlə/", "考拉"),
                w("outback", "/ˈaʊtbæk/", "内陆"),
                w("reef", "/riːf/", "礁"),
                w("indigenous", "/ɪnˈdɪdʒɪnəs/", "土著的"),
                w("multicultural", "/ˌmʌltiˈkʌltʃərəl/", "多元文化的"),
                w("continent", "/ˈkɒntɪnənt/", "洲"),
                w("southern hemisphere", "/ˈsʌðən ˈhemɪsfɪə/", "南半球"),
                w("aboriginal", "/ˌæbəˈrɪdʒɪnl/", "土著的"),
                w("vast", "/vɑːst/", "广阔的"),
                w("unique", "/juːˈniːk/", "独特的"),
                w("wildlife", "/ˈwaɪldlaɪf/", "野生动物"),
                w("harbour", "/ˈhɑːbə/", "海港"),
            ],
            "Unit 5 The taste of culture": [
                w("culture", "/ˈkʌltʃə/", "文化"),
                w("cuisine", "/kwɪˈziːn/", "菜肴"),
                w("ingredient", "/ɪnˈɡriːdiənt/", "食材"),
                w("recipe", "/ˈresɪpi/", "食谱"),
                w("spice", "/spaɪs/", "香料"),
                w("flavour", "/ˈfleɪvə/", "味道"),
                w("tradition", "/trəˈdɪʃn/", "传统"),
                w("festival", "/ˈfestɪvl/", "节日"),
                w("ritual", "/ˈrɪtʃuəl/", "仪式"),
                w("heritage", "/ˈherɪtɪdʒ/", "遗产"),
                w("diverse", "/daɪˈvɜːs/", "多样的"),
                w("exchange", "/ɪksˈtʃeɪndʒ/", "交流"),
                w("appreciate", "/əˈpriːʃieɪt/", "欣赏"),
                w("local", "/ˈləʊkl/", "当地的"),
                w("influence", "/ˈɪnfluəns/", "影响"),
            ],
            "Unit 6 When things go wrong": [
                w("accident", "/ˈæksɪdənt/", "事故"),
                w("emergency", "/ɪˈmɜːdʒənsi/", "紧急情况"),
                w("injury", "/ˈɪndʒəri/", "受伤"),
                w("first aid", "/fɜːst eɪd/", "急救"),
                w("ambulance", "/ˈæmbjʊləns/", "救护车"),
                w("fire brigade", "/faɪə brɪˈɡeɪd/", "消防队"),
                w("police", "/pəˈliːs/", "警察"),
                w("rescue", "/ˈreskjuː/", "救援"),
                w("safety", "/ˈseɪfti/", "安全"),
                w("risk", "/rɪsk/", "风险"),
                w("prevent", "/prɪˈvent/", "预防"),
                w("careful", "/ˈkeəfl/", "小心的"),
                w("warning", "/ˈwɔːnɪŋ/", "警告"),
                w("survive", "/səˈvaɪv/", "幸存"),
                w("crisis", "/ˈkraɪsɪs/", "危机"),
            ],
            "Unit 7 Celebrities": [
                w("celebrity", "/səˈlebrɪti/", "名人"),
                w("famous", "/ˈfeɪməs/", "著名的"),
                w("reputation", "/ˌrepjuˈteɪʃn/", "名誉"),
                w("achievement", "/əˈtʃiːvmənt/", "成就"),
                w("inspire", "/ɪnˈspaɪə/", "激励"),
                w("idol", "/ˈaɪdl/", "偶像"),
                w("influence", "/ˈɪnfluəns/", "影响"),
                w("career", "/kəˈrɪə/", "职业"),
                w("talent", "/ˈtælənt/", "才华"),
                w("admire", "/ədˈmaɪə/", "钦佩"),
                w("media", "/ˈmiːdiə/", "媒体"),
                w("interview", "/ˈɪntəvjuː/", "采访"),
                w("charity", "/ˈtʃærɪti/", "慈善"),
                w("role model", "/rəʊl ˈmɒdl/", "榜样"),
                w("privacy", "/ˈprɪvəsi/", "隐私"),
            ],
        },
    },
};
